[docs] cloud performance tab
yugabyte/yugabyte-db pull request #10516
Opened 2021-11-06 18:17 UTC by ddhodge

New Performance tab with metrics, live and slow queries

@netlify /latest/yugabyte-cloud/cloud-monitor/

2021-11-17 18:21 UTC, yb-andrew requested changes
The metric graphs should have exactly the same names as the platform metric graphs. Liza created a PR for Platform, you should be able to use the same information: https://github.com/yugabyte/yugabyte-db/pull/10471

There are no limits to the number of queries displayed in the tables. This can be a potential issue that we will address in the future.

Right now the "slow queries" show all the queries, not just the slow ones. So the name is a little misleading right now. We will be adding thresholds in a future release.

2021-11-17 18:21 UTC, yb-andrew commented on docs/content/latest/yugabyte-cloud/cloud-monitor/cloud-queries-live.md
> +- Visually identify relevant database operations.
Should mention that live queries only show queries "in-flight" or currently in progress. This means queries that execute quickly might not show up on load of page.

2021-11-17 22:12 UTC, aishwarya24 commented on docs/content/latest/yugabyte-cloud/cloud-monitor/_index.md
> +- A list of slow running queries that have been run on the cluster.
```suggestion
- A list of slow running YSQL queries that have been run on the cluster.
```

2021-11-17 22:12 UTC, aishwarya24 commented on docs/content/latest/yugabyte-cloud/cloud-monitor/manage-clusters.md
> +Yugabyte Cloud suppports horizontal scaling of clusters. If your workloads have increased, you can dynamically add nodes to a running cluster to improve latency, throughput, and memory. Likewise, if
Configure clusters has a broken link.

2021-11-18 01:31 UTC, yb-andrew approved these changes
LG

2021-11-18 03:27 UTC, aishwarya24 commented on docs/content/latest/yugabyte-cloud/cloud-monitor/overview.md
> +| YCQL Remote Operations | The number of remote read and write requests. Remote requests are re-routed internally to a different node for executing the operation. | If an application is using a Yugab
```suggestion
| YCQL Remote Operations | The number of remote read and write requests. Remote requests are re-routed internally to a different node for executing the operation. | If an application is using a Yugabyte driver that supports local query routing optimization and prepared statements, the expected value for this is close to zero. If using the Cassandra driver or not using prepared statements, expect to see a relatively even split between local and remote operations (for example, ~66% of requests to be remote for a 3-node cluster). 
```

2021-11-18 16:36 UTC, aishwarya24 approved these changes
LGTM

2021-12-02 23:00 UTC, merged