[docs] [integrations] Integrations page for Django with YugabyteDB
yugabyte/yugabyte-db pull request #11026
Opened 2022-01-07 18:37 UTC by aishwarya24

Resolves #9382 

- Verified the steps and modified parts of the document to make it compatible for Django 4.0
- Created a document for integrations section.

@netlify /latest/integrations/django-rest-framework/

2022-01-10 16:55 UTC, lizayugabyte requested changes
Made some comments

2022-01-10 16:55 UTC, lizayugabyte commented on docs/content/latest/integrations/django-rest-framework.md
> +- A users table should be created in your database. Verify that the table is created with the [ysqlsh](../../explore/ysql-language-features/databases-schemas-tables/#list-tables) client shell.
Suggestion:

Use the [ysqlsh](../../explore/ysql-language-features/databases-schemas-tables/#list-tables) client shell to verify that the users table has been created in your database.

2022-01-10 16:55 UTC, lizayugabyte commented on docs/content/latest/integrations/django-rest-framework.md
> +- Run the django project with the command:
Intro sentence before the list is missing

2022-01-10 16:55 UTC, lizayugabyte commented on docs/content/latest/integrations/django-rest-framework.md
> +- Insert a row with the command:
the following command:

2022-01-10 16:55 UTC, lizayugabyte commented on docs/content/latest/integrations/django-rest-framework.md
> +- Run the django project with the command:
the following command:

2022-01-10 16:55 UTC, lizayugabyte commented on docs/content/latest/integrations/django-rest-framework.md
> +- Verify that the new row is inserted with the command:
Suggestion: 
Verify that the new row has been inserted by executing the following command:

2022-01-12 17:24 UTC, aishwarya24 commented on docs/content/latest/integrations/django-rest-framework.md
> +For Django versions below 4.0 add the following code in `urls.py` instead, since you can import the urls using `django.conf.urls`:
Thank you for this one ,will remember this rule.

2022-01-12 19:02 UTC, aishwarya24 commented on docs/content/latest/integrations/django-rest-framework.md
> +
@Liza I have asked regarding what the minimum YugabyteDB version must be and will include when I have that detail. Regarding Django for backend version- I see one repo with instructions on installing it. There is no version mentioned : https://github.com/yugabyte/yb-django . So I think we can leave it as it is. I have modified the rest accordingly .

2022-01-19 21:12 UTC, lizayugabyte approved these changes
LGTM

2022-01-30 14:36 UTC, Sfurti-yb approved these changes
LGTM

2022-01-31 18:58 UTC, merged