[Docs] [Quick start] Build a python application page for ysql-django
yugabyte/yugabyte-db pull request #11059
Opened 2022-01-11 21:48 UTC by aishwarya24

Resolves #11027 

- Verified the steps and included a new build a python application page in latest and stable.
- Fixed broken links in Quick start and Build apps for versions 2.6, 2.4 and 2.2. 

@netlify /latest//quick-start/build-apps/python/ysql-django/

2022-01-13 02:27 UTC, polarweasel requested changes
This is looking really good. Just a few minor changes (and one that points to some changes required in the orm-examples repo, sorry!).

2022-01-13 02:27 UTC, polarweasel commented on docs/content/latest/quick-start/build-apps/python/ysql-django.md
> +- Create a database using the `YugabyteDB SQL shell`(ysqlsh) by navigating to the location of your local [YugabyteDB](#yugabytedb) cluster created above.
```suggestion
- Create a database using the YugabyteDB YSQL shell (ysqlsh). From the location of your local [YugabyteDB](#yugabytedb) cluster, run the following shell command:
```

2022-01-13 02:27 UTC, polarweasel commented on docs/content/latest/quick-start/build-apps/python/ysql-django.md
> +- From the `orm-examples/python/django` directory, create the migrations, and migrate the changes to the database using the following command:
```suggestion
- From the `orm-examples/python/django` directory, run the following command to create the migrations and migrate the changes to the database:
```

2022-01-13 14:05 UTC, aishwarya24 commented on docs/content/latest/quick-start/build-apps/python/ysql-django.md
> +- Generate a Django secret key using any django secret key generator and paste the generated key in the following line of the `settings.py` file:
Thank you ! I wasn't comfortable about this either. Will make the change.

2022-01-13 14:09 UTC, aishwarya24 commented on docs/content/latest/quick-start/build-apps/python/ysql-django.md
> +$ git clone https://github.com/yugabyte/orm-examples.git
Understood and noted. Thanks.

2022-01-14 16:03 UTC, aishwarya24 commented on docs/content/latest/quick-start/build-apps/python/ysql-django.md
> +$ curl --data '{ "firstName" : "John", "lastName" : "Smith", "email" : "jsmith@yb.com" }' \
This also requires us to change the domains in around 10 other quick start pages when I search for `orm-examples` in latest and stable alone. Shall I create a separate issue to fix those pages ? @polarweasel

2022-01-20 20:31 UTC, aishwarya24 commented on docs/content/latest/quick-start/build-apps/python/ysql-django.md
> +        'USER': 'postgres',
@Sfurti-yb , could you please confirm with this one. Pointed this question in the google doc as well.

2022-01-20 22:08 UTC, polarweasel approved these changes
LGTM, pending Sfurti's confirmation on the username...

2022-01-26 14:59 UTC, merged