[docs] Cloud Select database version
yugabyte/yugabyte-db pull request #11092
Opened 2022-01-14 17:38 UTC by ddhodge

Add select database version feature on cluster creation, and cluster creation/planning overview.

@netlify /latest/yugabyte-cloud/cloud-basics/

2022-01-17 21:05 UTC, polarweasel requested changes
Looking good, just some little stuff...

2022-01-17 21:05 UTC, polarweasel commented on docs/content/latest/yugabyte-cloud/cloud-basics/create-clusters.md
> +Save your database credentials in a safe place. If you lose these credentials you will not be able to use the database.
```suggestion
Save your database credentials in a safe place. If you lose these credentials, you won't be able to use the database.
```

2022-01-17 21:05 UTC, polarweasel commented on docs/content/latest/yugabyte-cloud/cloud-basics/create-clusters.md
> +After you complete the wizard, the **Clusters** page appears with the provisioning of your new cluster in progress.
```suggestion
After you complete the wizard, the **Clusters** page appears, showing the provisioning of your new cluster in progress.
```

2022-01-18 03:40 UTC, ddhodge commented on docs/content/latest/yugabyte-cloud/cloud-basics/create-clusters-overview.md
> +Yugabyte Cloud supports both vertical and horizontal scaling, so you can change these values after the cluster is created if your configuration doesn't match your performance requirements. This inclu
Ratchet

2022-01-27 23:37 UTC, merged