[Doc] PR for Document gflag validation support (Doc-PLAT-2474)
yugabyte/yugabyte-db pull request #11155
Opened 2022-01-20 19:50 UTC by lizayugabyte

Addresses https://yugabyte.atlassian.net/browse/PLAT-2474

Preview:

2022-01-24 20:53 UTC, lizayugabyte commented
@Lingeshwar Could you review the doc, please?

2022-01-25 04:25 UTC, Lingeshwar requested changes
@lizayugabyte , Here is my feedback

1. How to add gflags in create Universe ? (Missing here).
2. I have updated modal styles used here (Better to use that in documentation) because it has more real estate and clean.
3. Add Flags through free text is missing ? (For Bulk flag import).

rest LGTM

2022-01-25 20:16 UTC, lizayugabyte commented
@Lingeshwar I can't open the Add to Master dialog from Create Universe on dev server because it never loads:
![Screen Shot 2022-01-25 at 3 14 47 PM](https://user-images.githubusercontent.com/77016159/151052647-61d0a1d4-5c21-49bf-b609-46c14f1e7836.png)

2022-01-25 20:26 UTC, lizayugabyte commented
@Lingeshwar 
The "Add flags via Text" description was included in the first version of the doc. 
Added a section on adding flags to a new universe.
Can't change the screen shots because the UI doesn't load.

2022-01-26 15:42 UTC, lizayugabyte commented
Via slack today:
Lingesh  9:34 AM
New changes are not yet deployed in portal
Add as Free text option is now going to replace with Add as JSON and ui is not similar with earlier ui.

2022-01-26 17:08 UTC, Lingeshwar commented
@lizayugabyte , Sorry for the inconvenience caused. 
Today I have been asked to make the changes from "ADD as free text" to "Add as JSON". 
I will let you know once it is done and I will send you all the new screenshots.
Thank you

2022-02-04 03:20 UTC, Lingeshwar reviewed
@lizayugabyte , Can you please provide some information about Add as JSON option and attach it's screenshot.
rest LGTM

Check the below image
<img width="1106" alt="Screenshot 2022-02-04 at 8 48 07 AM" src="https://user-images.githubusercontent.com/30400240/152466621-9afdbaf0-56b9-4c47-a41e-b020b2fe5a03.png">

2022-02-04 13:58 UTC, Lingeshwar requested changes

2022-02-04 13:58 UTC, Lingeshwar commented on docs/content/latest/yugabyte-platform/manage-deployments/edit-config-flags.md
> +- Use **Add as JSON > Add to Master** and **Add as JSON > Add to T-Server** to import flags in bulk. The flugs must be defined as name-value pairs in a JSON format via the in the **Add to T-Server**
Just typo change
change flugs to flags and name-value pairs to key-value pairs

2022-02-04 14:58 UTC, Lingeshwar approved these changes
LG

2022-02-04 19:29 UTC, merged