[docs] add macOS monterey note to fix the 7000 port in use issue.
yugabyte/yugabyte-db pull request #11209
Opened 2022-01-25 15:43 UTC by aishwarya24

Resolves #11062 

- Added a note for the macOS quickstart page and in troubleshooting. 
- Changes are in latest currently. Will include them to stable once this is approved.

@netlify /latest/troubleshoot/nodes/check-processes/

2022-02-22 20:14 UTC, vkulichenko requested changes
Not every user will want to disable the AirPlay. We should also provide an alternative option of changing the port number for the UI. Here is the command to customize the port:

`./bin/yugabyted start --master_webserver_port=9999`

2022-02-23 17:29 UTC, aishwarya24 commented
@vkulichenko @polarweasel @dmagda , I have added the suggestion mentioned by @vkulichenko as well. This is probably the same as @dmagda mentioned earlier in the [issue](https://github.com/yugabyte/yugabyte-db/issues/11062).
Please review.

2022-02-23 21:11 UTC, polarweasel commented on docs/content/latest/troubleshoot/nodes/check-processes.md
> +The workaround is to turn AirPlay receiving off, then start YugabyteDB, and then (optionally) turn AirPlay receiving back on.Alternatively(recommended), you can change the default port number using t
```suggestion
The workaround is to turn AirPlay receiving off, then start YugabyteDB, and then (optionally) turn AirPlay receiving back on. Alternatively(recommended), you can change the default port number using the `--master_webserver_port` flag when you start the cluster as follows:
```

2022-02-23 21:11 UTC, polarweasel approved these changes
LGTM!

2022-02-23 21:31 UTC, merged