[Platform] Updated the azcopy and node-exporter version
yugabyte/yugabyte-db pull request #11375
Opened 2022-02-07 05:33 UTC by baba230896

### Summary

- Updated the azcopy (10.4.0 to 10.13.0), helm (3.2.0 to 3.8.0) and node-exporter (1.2.2 to 1.3.1) to newer versions.

2022-02-08 12:26 UTC, bhavin192 approved these changes
Looks good to me since the updated versions are backward compatible with each other.

2022-02-10 09:22 UTC, anmalysh-yb commented
Note that you should add new node exporter version to thirdparty deps package, like it's done here: https://bitbucket.org/yugabyte/%7Bff95732b-44b2-4b69-9b2e-e4f83aca72ee%7D/commits/11948d987e3cde300aa808f6bc96f4f5d5c6d0b5 before you commit this one.

I think same applies for azcopy as well.

Also, don't forget to update https://s3.console.aws.amazon.com/s3/object/downloads.yugabyte.com?region=us-west-2&prefix=platform-support-packages.tar.gz with these new versions.

2022-02-10 09:24 UTC, anmalysh-yb requested changes
One comment, which need to be addressed before landing that.

2022-02-10 14:17 UTC, baba230896 commented
> Don't forget to update https://s3.console.aws.amazon.com/s3/object/downloads.yugabyte.com?region=us-west-2&prefix=platform-support-packages.tar.gz with these new versions.

@anmalysh-yb Is this tar manually created or by some automation?

2022-02-10 14:18 UTC, anmalysh-yb commented
It's created manually for now. Just download the current version and upload the updated version back

2022-02-11 12:52 UTC, merged