[11559-xCluster][Doc] Documentation on how to setup xCluster in K8s when you have pod to pod connectivity
yugabyte/yugabyte-db pull request #11616
Opened 2022-03-01 12:06 UTC by Arjun-yb

Adding section to the xCluster setup docs for how to setup xCluster in K8s when you have pod to pod connectivity.

2022-03-04 11:55 UTC, Arjun-yb commented on docs/content/latest/deploy/multi-dc/async-replication.md
> +1. Create 2 Universes (source and target)
Done

2022-03-04 11:56 UTC, Arjun-yb commented on docs/content/latest/deploy/multi-dc/async-replication.md
> +  (At source)
Added

2022-03-04 11:56 UTC, Arjun-yb commented on docs/content/latest/deploy/multi-dc/async-replication.md
> +  ```.sh
Changed

2022-03-04 11:57 UTC, Arjun-yb commented on docs/content/latest/deploy/multi-dc/async-replication.md
> +  For Example
Done

2022-03-04 11:59 UTC, Arjun-yb commented on docs/content/latest/deploy/multi-dc/async-replication.md
> +5. Do some DML at source side and observe the replication at target side
Updated

2022-03-04 11:59 UTC, Arjun-yb commented on docs/content/latest/deploy/multi-dc/async-replication.md
> +4. Setup Replication from source universe
Done

2022-03-04 11:59 UTC, Arjun-yb commented on docs/content/latest/deploy/multi-dc/async-replication.md
> +3. Collect table UUIDs, go to the `Tables` section in the Admin UI (127.0.0.1:7000)
Done

2022-03-04 16:04 UTC, ajcaldera1 requested changes
So we probably should put a link to how it is done via platform as well: https://docs.yugabyte.com/latest/yugabyte-platform/create-deployments/async-replication-platform/ 
This can be done at the bottom of the page. Something like: For users of Yugabyte Platform (2.11+), please visit the following link to configure replication. 

The other thing we need to talk about is how networking needs to be setup. So the instructions from multi-gke cluster setup need to be followed with some modifications to make sure that `kube-dns` is properly configured with stub domains to enable cross cluster DNS.  The python script on that page needs a small modification to handle setting up multiple clusters simultaneously. Working on perfecting/writing that up.

2022-03-04 19:02 UTC, Arjun-yb commented
Thanks @ajcaldera1 
 Added the instruction for how to setup xCluster via Platform.
 Once I get the instructions for multi-gke cluster setup, I can work on documenting that.

2022-03-07 17:04 UTC, bmatican commented
@ajcaldera1 Let's decouple the multi-cluster docs from this, so we can make incremental progress! If this is good enough to be useful, for k8s setup, please stamp this as is and we can file a new issue for follow up.

2022-03-07 17:06 UTC, ajcaldera1 approved these changes
LGTM

2022-03-07 17:08 UTC, bmatican commented
Thanks Alan!

2022-03-08 07:38 UTC, merged