Apache superset documentation to third party tools section
yugabyte/yugabyte-db pull request #11728
Opened 2022-03-11 11:08 UTC by aatrey-yb

2022-03-11 11:10 UTC, aatrey-yb commented
@netlify /latest/tools/superset/

2022-03-14 09:26 UTC, aatrey-yb commented
@netlify /latest/tools/superset/

2022-03-17 01:45 UTC, polarweasel requested changes

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +    weight: 2794
Let's put this right before Arctype in the left nav
```suggestion
    weight: 2709
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +Your YugabyteDB cluster should be up and running. If you're new to YugabyteDB, create a local cluster in less than five minutes following the steps in [Quick Start](../../quick-start/install). You ca
```suggestion
Your YugabyteDB cluster should be up and running. If you're new to YugabyteDB, create a local cluster in less than five minutes following the steps in [Quick Start](../../quick-start/install). You can also get started with the free tier of [YugabyteDB Fully-Managed Cloud](https://www.yugabyte.com/cloud/).

You also need to load a relevant database in your YugabyteDB for exploration and visualization. You can load the Northwind sample database with the `./bin/yugabyted demo connect` command from your shell, or you can follow the [instructions here](https://docs.yugabyte.com/latest/sample-data/northwind/).
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +You also need to install Apache Superset to explore and visualize your data. You can install Superset using [Docker Compose](https://superset.apache.org/docs/installation/installing-superset-using-do
What version of Python is required for this? If it's 3, as I suspect, change `(pip)` to `(pip3)` as a little clue for the reader.

```suggestion
You also need to install Apache Superset to explore and visualize your data. You can install Superset using [Docker Compose](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose) (recommended) or from scratch using [Python (pip)](https://superset.apache.org/docs/installation/installing-superset-from-scratch).
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +## Connecting Apache Superset with YugabyteDB
```suggestion
## Connect Apache Superset to YugabyteDB
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +After successful installation, launch Superset in the browser at http://<hostname/IP>:8088. In case of local installation on your laptop, navigate to localhost:8088 or 127.0.0.1:8088. Superset comes
```suggestion
After successful installation, launch Superset in your browser at `http://<hostname-or-IP-address>:8088`. If you've installed on your local computer, navigate to `localhost:8088` or `127.0.0.1:8088`. Superset comes with a standard PostgreSQL driver that also connects to YugabyteDB. You can also manually install the [psycopg2 driver](https://www.psycopg.org/docs/) to connect to YugabyteDB.
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +Follow these steps to connect Apache Superset to YugabyteDB:
```suggestion
To connect Apache Superset to YugabyteDB:
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +1. Navigate to Data → Databases → + Databases and choose "PostgreSQL" from the “Connect a database” menu as shown below.
Don't use the arrows if possible. They won't render correctly on all browsers/machines. The usual convention is > instead.
```suggestion
1. Navigate to Data > Databases > + Databases, and choose "PostgreSQL" from the “Connect a database” menu.
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +3. You should now be connected to the YugabyteDB and to verify you can check the availabe databases and schemas under "Data". Navigate to Data → Datasets and click "+Datasets" and in the dialog confi
Number everything with `1.` — it makes editing lists a lot easier later on!

```suggestion
1. Enter your YugabyteDB tablet server's hostname or IP address with standard credentials and click "Finish".

    ![Database Connection Credentials](/images/develop/tools/superset/connect-ybdb.png)

    {{< note title="Note" >}}
As of Docker version 18.03, the `host.docker.internal` hostname connects to your Docker host from inside a Docker container.
    {{< /note >}}

1. Verify that you can access the available databases and schemas under "Data". Navigate to Data > Datasets, and click "+Datasets".

    The dropdown list should show the databases and schemas available to explore and visualize.
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +Superset is a rich, open-source data exploration and visualization platform that allows Business Analysts, Data Scientists and Developers to quickly explore and visualize data stored in their databas
Don't capitalize things unless they're proper nouns or trademarked terms...

```suggestion
Superset is a rich, open-source data exploration and visualization platform that allows business analysts, data scientists, and developers to quickly explore and visualize data stored in their databases and data warehouses. You can explore data without writing complex SQL queries, create rich reports and custom dashboards to visualize this data, and get insights quickly.
```

2022-03-17 01:45 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +Refer to Apache Superset [documentation](https://superset.apache.org/docs/creating-charts-dashboards/exploring-data#exploring-data-in-superset) to learn more about Superset's data exploration capabil
```suggestion
Refer to the Apache [Superset documentation](https://superset.apache.org/docs/creating-charts-dashboards/exploring-data#exploring-data-in-superset) to learn more about Superset's data exploration capabilities. If you're creating your first dashboard using Superset, check out the [data analysis and exploration workflow](https://superset.apache.org/docs/creating-charts-dashboards/creating-your-first-dashboard/).
```

2022-03-17 01:46 UTC, polarweasel commented on docs/content/latest/tools/superset.md
> +3. You should now be connected to the YugabyteDB and to verify you can check the availabe databases and schemas under "Data". Navigate to Data → Datasets and click "+Datasets" and in the dialog confi
(Also, the weird formatting of the note is correct. If you indent the _content_, it'll render as a code block!)

2022-03-18 21:17 UTC, polarweasel approved these changes

2022-03-18 21:17 UTC, merged