[Docs] SSL-config related changes in the SequelizeORM docs
yugabyte/yugabyte-db pull request #12811
Opened 2022-06-08 06:07 UTC by priyanshi-yb

This PR includes the changes to mention the steps of how to connect the Sequelize ORM app with YugabyteDB Cloud Cluster.

2022-06-08 06:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=12811) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=12811) before we can accept your contribution.<br/><hr/>**Priyanshi Gupta** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yugabyte/yugabyte-db?pullRequest=12811) it.</sub>

2022-06-14 07:27 UTC, ashetkar commented on docs/content/preview/quick-start/build-apps/nodejs/ysql-sequelize.md
> +This tutorial assumes that you have installed YugabyteDB and created a cluster. Refer to [Quick Start](../../../../quick-start/). Also, you have installed latest stable version of [node](https://node
Please make these two as separate points.

2022-06-14 07:27 UTC, ashetkar commented on docs/content/preview/drivers-orms/nodejs/sequelize-yugabytedb.md
> +## Using Cloud Cluster to connect with Seqeulize:
Can this be something like "Specifying SSL configuration"?
And then we can mention that this is required if one is connecting to a YB Managed cluster or even a local YB cluster with SSL enabled.

2022-06-22 01:17 UTC, polarweasel requested changes

2022-06-22 01:17 UTC, polarweasel commented on docs/content/preview/drivers-orms/nodejs/sequelize-yugabytedb.md
> +```
Gotta use markdownlint... Also, this should be a numbered list.

````suggestion

## Specifying SSL configuration

This configuration can be used while connecting to a YB Managed cluster or a local YB cluster with SSL enabled.

1. Install the `fs` package to read the SSL certificate:

    ```sh
    npm install fs
    ```

1. Add the following line to use the `fs` module:

    ```js
    const fs = require('fs');
    ```

1. Use the following configuration in the `models/index.js` file when you create the sequelize object:

    ```js
    const sequelize = new Sequelize("<db_name>", "<user_name>","<password>" , {
        dialect: 'postgres',
        port: 5433,
        host: "<host_name>",
        dialectOptions: {
            ssl: {
                rejectUnauthorised: true,
                ca: fs.readFileSync('<path_to_root_crt>').toString(),
            }
        }
      });
    ```
````

2022-06-22 01:17 UTC, polarweasel commented on docs/content/preview/quick-start/build-apps/nodejs/ysql-sequelize.md
> +```
Markdownlint is helpful, and we have rules already defined for it in the repo...

(And again, should it be unauthoriZed?)

````suggestion

## Specifying SSL configuration

This configuration can be used while connecting to a YB Managed cluster or a local YB cluster with SSL enabled.

Use the configuration in the following way in the `models/index.js` file when you create the sequelize object:

```js
sequelize = new Sequelize("<db_name>", "<user_name>","<password>" , {
    dialect: 'postgres',
    port: 5433,
    host: "<host_name>",
    dialectOptions: {
        ssl: {
            rejectUnauthorised: true,
            ca: fs.readFileSync('<path_to_root_crt>').toString(),
        }
    }
  });
```
````

2022-06-22 11:43 UTC, priyanshi-yb commented
@aishwarya24, commit the suggested change.

2022-06-22 15:10 UTC, aishwarya24 commented on docs/content/preview/drivers-orms/nodejs/sequelize.md
> +```
@priyanshi-yb , Could you please confirm with Alex's question about the usage of rejectUnauthorised ? If it works , then please go ahead and merge this one.

2022-06-22 15:32 UTC, merged