[Docs] Added the docs for Prisma ORM for Node.js
yugabyte/yugabyte-db pull request #12847
Opened 2022-06-10 04:34 UTC by priyanshi-yb

This PR includes the docs in [Quickstart - build an application](https://docs.yugabyte.com/preview/quick-start/build-apps/nodejs/) and [Drivers and Orms](https://docs.yugabyte.com/preview/drivers-orms/nodejs/) sections for Prisma ORM for Nodejs. This PR depends on the [PR](https://github.com/yugabyte/orm-examples/pull/94) of orm-example Prisma ORM for Nodejs.

2022-06-10 04:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=12847) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=12847) before we can accept your contribution.<br/><hr/>**Priyanshi Gupta** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yugabyte/yugabyte-db?pullRequest=12847) it.</sub>

2022-06-21 05:35 UTC, priyanshi-yb commented
@polarweasel , orm-example [PR](https://github.com/yugabyte/orm-examples/pull/94) is merged and now this PR is ready to be reviewed.

2022-06-22 00:42 UTC, polarweasel commented
Thanks @aishwarya24 for taking the review for this one!

2022-06-22 10:58 UTC, aishwarya24 requested changes

2022-06-22 11:28 UTC, aishwarya24 commented
@priyanshi-yb , Please sign the CLA.

2022-06-22 14:02 UTC, priyanshi-yb commented
@aishwarya24, made the suggested changes.

2022-06-22 19:06 UTC, polarweasel approved these changes
I'll apply all these suggestions, and then merge

2022-06-22 19:06 UTC, polarweasel commented on docs/content/preview/quick-start/build-apps/nodejs/ysql-prisma.md
> +{{< /note >}}
````suggestion
## Apply the migrations 

Create the tables in YugabyteDB by applying the migration for the data models in the file `prisma/schema.prisma`, and generate the Prisma client using the following command:

```sh
$ npx prisma migrate dev --name first_migration
```

 {{< note title="Note" >}}

To use the Prisma CLI without `npx`, install Prisma globally, as follows:

```sh
npm install -g prisma
```

{{< /note >}}

````

2022-06-22 19:06 UTC, polarweasel commented on docs/content/preview/quick-start/build-apps/nodejs/ysql-prisma.md
> +```
````suggestion
Start the Node.js API server at <http://localhost:8080>.

```sh
$ npm start
```

If port 8080 is already in use, change the port using the following command:

```sh
$ export PORT=<new_port>
```

````

2022-06-22 19:37 UTC, merged