[docs][cloud] Performance Advisor
yugabyte/yugabyte-db pull request #12961
Opened 2022-06-20 17:16 UTC by ddhodge

New performance advisor page/feature

@netlify /preview/yugabyte-cloud/cloud-monitor/cloud-advisor/

2022-06-20 18:18 UTC, sushantrmishra requested changes

2022-06-20 18:18 UTC, sushantrmishra commented on docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
> +Advisor scans queries to determine whether some nodes are handling more queries than others. Advisor flags nodes that processed 50% more queries than the other nodes in the past hour.
We changed the implementation a bit. 

Advisor flags nodes that processed 50% more queries than the other nodes in the past hour or when the perf advisor scan was performed  last time.

2022-06-20 20:11 UTC, yb-andrew reviewed
There's also a high CPU usage recommendation type, which can happen independent of CPU skew.

2022-06-20 21:15 UTC, sushantrmishra approved these changes

2022-06-20 23:29 UTC, yb-andrew approved these changes
Looks good.

2022-06-21 17:31 UTC, lizayugabyte commented on docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
> +**Why**
Is this an unfinished sentence?

2022-06-21 17:33 UTC, lizayugabyte commented on docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
> +- When doing an INSERT or DELETE on a table, indexes need to be updated to remain consistent with the data in the main table. An index can also prevent a basic insert or delete from being executed as
Suggestion:  ... a basic insert or delete operation

2022-06-21 17:33 UTC, lizayugabyte commented on docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
> +- When doing an UPDATE on a table, if the modified column is part of the index, then the index must be updated as well.
`UPDATE`

2022-06-21 17:34 UTC, lizayugabyte commented on docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
> +Connect to the database and use DROP INDEX to delete the unused indexes.
`DROP INDEX`

2022-06-21 17:35 UTC, lizayugabyte commented on docs/content/preview/yugabyte-cloud/cloud-monitor/cloud-advisor.md
> +**Why**
The Why pseudo-headers look weird

2022-06-21 19:16 UTC, nchandrappa commented
LGTM.

2022-06-21 21:46 UTC, merged