[#13047][Docs][DocDB] Documentation for tablet split gflags and usage in 2.14
yugabyte/yugabyte-db pull request #13277
Opened 2022-07-13 14:22 UTC by jmeehan16

Documentation changes for tablet splitting in 2.14. Includes descriptions for each of the relevant gflags and some updates to tablet splitting page with recommendations for best configurations for performance.

2022-07-13 14:29 UTC, jmeehan16 commented on docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
> +* By default, tablet splitting is disabled by default for tables with cross cluster replication. It can be enabled by setting both [`enable_tablet_split_of_xcluster_replicated_tables`](../../../refer
"by default" twice here

2022-07-13 15:17 UTC, SrivastavaAnubhav approved these changes
Looks good, just minor comments.

2022-07-13 15:17 UTC, SrivastavaAnubhav commented on docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
> +By default, a given table will be considered to be in the low phase until there are 8 tablets per node. In this phase, a tablet will be split once it reaches 512 MB in size.
I think it's clear enough to say that the default values of `tablet_split_low_phase_shard_count_per_node` is 8, and the default value of `tablet_split_low_phase_size_threshold_bytes` is `512 MB`.

2022-07-13 15:17 UTC, SrivastavaAnubhav commented on docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
> +By default, a table will be considered to be in the high phase until there are 24 tablets per node. In this phase, a tablet will be split once it reaches 10 GB in size.
Same comment as above (we should be clear that 10 GB is just the default value of `tablet_split_high_phase_size_threshold_bytes`).

2022-07-13 15:17 UTC, SrivastavaAnubhav commented on docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
> +By default, a given table will be considered in this final phase once there are more than 24 tablets per node (determined by `tablet_split_high_phase_shard_count_per_node`). Once in this phase, a tab
"considered **to be** in"?
"once there are more than 24" -> "once there are more than `tablet_split_high_phase_shard_count_per_node`"

Same comment about being clear that the numbers we're quoting are just defaults controlled by the flags.

2022-07-13 15:17 UTC, SrivastavaAnubhav commented on docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
> +Once a split has been executed on a tablet, the two resulting tablets will require a full compaction in order to remove unnecessary data from each. These post-split compactions can require fairly sig
Can shorten "can require fairly significant CPU and disk resources, and impact workload performance as a result". E.g to "can significantly increase CPU and disk usage and thus impact performance".

2022-07-13 18:36 UTC, hulien22 requested changes

2022-07-13 18:36 UTC, hulien22 commented on docs/content/preview/architecture/docdb-sharding/tablet-splitting.md
> +* By default, tablet splitting is disabled by default for tables with cross cluster replication. It can be enabled by setting both [`enable_tablet_split_of_xcluster_replicated_tables`](../../../refer
`enable_tablet_split_of_xcluster_bootstrapping_tables` should be kept as false until https://github.com/yugabyte/yugabyte-db/issues/13170 gets landed, as xcluster bootstrapping + tablet splitting is currently unsupported

2022-07-13 19:22 UTC, polarweasel commented
You guys all need to use the "Suggest change" button :)

2022-07-13 20:16 UTC, jmeehan16 commented on docs/content/preview/reference/configuration/yb-master.md
>  Enables YugabyteDB to [automatically split tablets](../../../architecture/docdb-sharding/tablet-splitting/#automatic-tablet-splitting) while online, based on the specified tablet threshold sizes conf
Good question, haha. I think we can just remove those words.

2022-07-28 02:27 UTC, polarweasel commented
@jmeehan16 `docs/content/preview` is v2.15, and `docs/content/stable` is v2.14. Did you need these changes in 2.15 (preview), 2.14 (stable), or both?

2022-08-01 19:35 UTC, jmeehan16 commented
> docs/content/preview is v2.15, and docs/content/stable is v2.14. Did you need these changes in 2.15 (preview), 2.14 (stable), or both?
@polarweasel - Good point. This needs to be applied to both 2.15 (preview) and 2.14 (stable).

2022-08-04 23:51 UTC, polarweasel approved these changes
I've applied the changes to stable now. LGTM!

2022-08-04 23:56 UTC, merged