[docs] Doc for a raft flag: --evict_failed_follower
yugabyte/yugabyte-db pull request #15258
Opened 2022-12-08 15:32 UTC by aishwarya24

resolves #15207

2022-12-13 18:07 UTC, ionthegeek requested changes
A couple of small but important changes needed in the master doc.

2022-12-13 18:07 UTC, ionthegeek commented on docs/content/preview/reference/configuration/yb-master.md
> +Note that it is not recommended to set the flag to true for masters as you cannot automatically recover a failed master once its evicted.
Typo here - "its" should be "it's" or "it has been"

2022-12-13 18:07 UTC, ionthegeek commented on docs/content/preview/reference/configuration/yb-master.md
> +Default: `true`
The default for masters is `false`.

2022-12-13 18:19 UTC, ionthegeek approved these changes
Looks good!

2022-12-14 18:48 UTC, ddhodge approved these changes
LGTM

2022-12-14 20:25 UTC, merged