[docs][DB-5232] changes to the YCQL Snapshot based backup/restore document
yugabyte/yugabyte-db pull request #15968
Opened 2023-02-03 15:55 UTC by aishwarya24

resolves https://yugabyte.atlassian.net/browse/DB-5232

Note to self: back-port till 2.12

Build preview : https://deploy-preview-15968--infallible-bardeen-164bc9.netlify.app/preview/manage/backup-restore/snapshots-ycql/
@netlify /preview/manage/backup-restore/snapshots-ycql/

2023-02-06 23:53 UTC, vpatibandla-yb commented on docs/content/preview/manage/backup-restore/snapshots-ycql.md
> +        10.9.206.43:/mnt/d0/yb-data/tserver/data/rocksdb/table-00004000000030008000000000004001/ \
Change the IP to target node ip

2023-02-06 23:53 UTC, vpatibandla-yb commented on docs/content/preview/manage/backup-restore/snapshots-ycql.md
> +        10.9.206.43:/mnt/d0/yb-data/tserver/data/rocksdb/table-00004000000030008000000000004001/ \
Same as above

2023-02-06 23:56 UTC, vpatibandla-yb reviewed
Few minor comments

2023-02-06 23:59 UTC, vpatibandla-yb requested changes
Also make changes for YSQL

2023-02-07 12:40 UTC, ag26jan reviewed
Please make the changes [vpatibandla-yb](https://github.com/vpatibandla-yb) pointed. Rest looks good to me as well.

2023-02-07 21:08 UTC, lizayugabyte approved these changes

2023-02-08 03:38 UTC, vpatibandla-yb approved these changes

2023-02-08 20:53 UTC, merged