[docs][yba] Update On-prem provider in 2.16
yugabyte/yugabyte-db pull request #17715
Opened 2023-06-07 20:35 UTC by ddhodge

Updates to On-Premises provider configuration instructions in 2.16:
- remove node agent
- update centos 7 VM instructions [PLAT-9190]

@netlify /preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/on-premises/#configure-hardware-for-yugabytedb-nodes

2023-06-07 23:50 UTC, amannijhawan commented
Doc Fixes Look good to me.

2023-06-08 04:28 UTC, chidmuthu requested changes
These files should be present for any operating system not just CentOS 7. The only difference is the location of the files. /etc/systemd/system/ for root level systemd (need the sudo whitelist, which needs to be updated as well I think) or /home/yugabyte/.config/systemd/user if they want user level systemd without the whitelist

2023-06-08 06:14 UTC, chidmuthu commented
Looks good to me!

2023-06-08 06:14 UTC, chidmuthu approved these changes

2023-06-08 14:17 UTC, merged