Fix query_id propagation from PG to TServer as part of AUH metadata
yugabyte/yugabyte-db pull request #18113
Opened 2023-07-06 09:12 UTC by abhinab-yb

pg_stat_statements doesn't store the query id in the `Query` object in case of utility statements. This PR fixes that and also setting the query_id correctly in AUH metadata.

2023-07-13 15:35 UTC, vrajat requested changes
Can you add back `MyProc->queryid = ...` and also add it to the new places where queryid is set.

2023-07-13 15:35 UTC, vrajat commented on src/postgres/src/backend/parser/analyze.c
> -	if (IsYugaByteEnabled())
Why was this code deleted? If you have moved it somewhere else, can you also set queryid in `MyProc` ?

2023-07-13 15:35 UTC, vrajat commented on src/yb/yql/pggate/pg_session.cc
> +
nit: Whitespace change

2023-07-14 04:20 UTC, amitanandaiyer approved these changes
lgtm

2023-07-14 04:50 UTC, merged