yb-admin get_xcluster_info should return valid JSON
yugabyte/yugabyte-db pull request #18671
Opened 2023-08-11 21:45 UTC by kerneljake

Currently `yb-admin get_xcluster_info` returns invalid JSON which makes parsing long output with tools like `jq` difficult.

Steps to reproduce

Before:
```
$ yb-admin get_xcluster_info | jq
parse error: Invalid numeric literal at line 1, column 63
```

After:
```
$ yb-admin get_xcluster_info | jq
{
  "version": 0,
  "xcluster_producer_registry": {},
  "consumer_registry": {}
}
```

2023-09-06 19:03 UTC, hari90 requested changes
Thank you for fixing this.
Can you please file a GH item for it as well?
And change the title to this format:

`[#<GH issue number>] xCluster: yb-admin get_xcluster_info should return valid JSON`

2023-09-06 19:50 UTC, hari90 approved these changes
:+1:

2023-09-11 16:12 UTC, premkumr commented
LGTM. Good fix. Thanks @kerneljake !

2023-09-11 16:13 UTC, premkumr approved these changes

2023-09-11 16:58 UTC, merged