add sample rate
yugabyte/yugabyte-db pull request #18750
Opened 2023-08-18 10:33 UTC by nandhiniS1212

2023-08-18 10:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=18750) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=18750) before we can accept your contribution.<br/><hr/>**Nandhini Shenoy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yugabyte/yugabyte-db?pullRequest=18750) it.</sub>

2023-08-18 10:56 UTC, abhinab-yb commented on src/postgres/contrib/yb_auh/yb_auh.c
> -
nit: removed line

2023-08-18 10:56 UTC, abhinab-yb commented on src/postgres/contrib/yb_auh/yb_auh.c
> +
nit: extra white space

2023-08-21 04:22 UTC, hbhanawat requested changes
1. You are not sampling the events based on the sample size? If sample_size_procs is 5, only 5 events should be inserted in the circular buffer. I don't see that happening. 
2. Secondly, I don't think we need two variables sample_size_procs and sample_size_rpcs. For making it configurable you can follow the same approach as that of yb_auh.sampling_interval

2023-08-22 10:05 UTC, abhinab-yb approved these changes

2023-08-23 05:39 UTC, merged