Update using procArray, add wait state info check for optimisation
yugabyte/yugabyte-db pull request #18835
Opened 2023-08-24 05:06 UTC by nandhiniS1212

2023-08-24 05:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=18835) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=18835) before we can accept your contribution.<br/><hr/>**Nandhini Shenoy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yugabyte/yugabyte-db?pullRequest=18835) it.</sub>

2023-08-24 05:36 UTC, amitanandaiyer commented on src/postgres/contrib/yb_auh/yb_auh.c
> +static void pg_collect_samples(TimestampTz auh_sample_time, uint16 sample_size_procs)
num_procs_to_sample/collect would be more descriptive.

2023-08-24 05:55 UTC, abhinab-yb requested changes

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> +	LWLockAcquire(ProcArrayLock, LW_SHARED);
This can go down one line, better to hold the locks for as little as possible

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> +	for (int i = 0; i < procArray->numProcs; i++)
Can you follow the same pattern as the other functions which iterate over the procarray?

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> +		PGPROC *proc  = &allProcs[pgprocno];
volatile

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> +	ereport(LOG, (errmsg("numprocs %d", arrayP->numProcs)));
is this needed?

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> +    PgProcAuhNode *newNode = malloc(sizeof(PgProcAuhNode));
palloc

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> +        free(temp);
pfree

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/contrib/yb_auh/yb_auh.c
> +    }
This will be same for a single iteration of `pg_collect_samples ` correct? If yes, can we move this out of the loop?

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> +void insertNode(PgProcAuhNode **head, PGProcAUHEntryList data) {
This can be 

`void insertNode(PgProcAuhNode **head, PGProcAUHEntryList data) {`

and you can use `insertNode(head, data)`

2023-08-24 05:55 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> +			PGProcAUHEntryList entry = proc_getter(proc, procArray->numProcs);
We don't want numProcs, but the final size of the linked list which won't be equal to numprocs always

2023-08-29 04:38 UTC, abhinab-yb approved these changes

2023-08-29 04:38 UTC, abhinab-yb commented on src/postgres/src/backend/storage/ipc/procarray.c
> -
nit: removed line

2023-08-29 06:20 UTC, hbhanawat commented on src/postgres/src/include/pg_yb_utils.h
> +typedef struct PgProcAuhNode
Why do we need a linked list? An array might work here.

2023-08-29 06:28 UTC, hbhanawat commented on src/postgres/src/backend/storage/ipc/procarray.c
> +PGProcAUHEntryList proc_getter(volatile PGPROC *proc)
Can we name it as fetch_proc_entries

2023-08-30 08:01 UTC, merged