[docs] updates to packed row from beta to Early access.
yugabyte/yugabyte-db pull request #19395
Opened 2023-10-03 19:07 UTC by aishwarya24

2023-10-03 20:06 UTC, rthallamko3 commented on docs/content/preview/reference/configuration/yb-tserver.md
> +<sup>$</sup> Read Committed Isolation is supported only if the YB-TServer flag `yb_enable_read_committed_isolation` is set to `true`. By default this flag is `false` and in this case the Read Committ
Are you including read committed documentation updates too?

2023-10-03 20:06 UTC, rthallamko3 commented on docs/content/preview/reference/configuration/yb-tserver.md
> -##### --remote_bootstrap_from_leader_only
Why is this being removed?

2023-10-03 20:07 UTC, rthallamko3 commented on docs/content/preview/reference/configuration/yb-tserver.md
> +For versions 2.16 and 2.18, the feature is stable to be used in production, and starting from version 2.19 and later, the flag default is true.
true for new clusters.

2023-10-03 20:11 UTC, rthallamko3 requested changes
remove the unrelated changes.

2023-10-03 20:44 UTC, rthallamko3 requested changes
need to fix a couple of links.

2023-10-03 20:44 UTC, rthallamko3 commented on docs/content/preview/reference/configuration/yb-tserver.md
>  To learn about the packed row feature, see [Packed row format](../../../architecture/docdb/persistence/#packed-row-format-beta) in the architecture section.
This link needs to be updated in a couple of places. Can you search for #packed-row-format-beta and fix them all?

2023-10-03 20:48 UTC, rthallamko3 requested changes

2023-10-03 20:48 UTC, rthallamko3 commented on docs/content/preview/reference/configuration/yb-tserver.md
> +For versions 2.16.4 and later, and 2.18.1 and later, the feature is stable to be used in production, and starting from version 2.19 and later, the flag default is true for new clusters.
Packed Row for YSQL can be used 2.16.4 release onwards in production environments, if the cluster is not used in xCluster settings. For xCluster scenarios, use 2.18.1 and later. Starting from version 2.19 and later, the flag default is true for new clusters.

2023-10-03 20:48 UTC, rthallamko3 commented on docs/content/stable/reference/configuration/yb-tserver.md
> +For versions 2.16.4 and later, and 2.18.1 and later, the feature is stable to be used in production, and starting from version 2.19 and later, the flag default is true for new clusters.
Packed Row for YSQL can be used 2.16.4 release onwards in production environments, if the cluster is not used in xCluster settings. For xCluster scenarios, use 2.18.1 and later. Starting from version 2.19 and later, the flag default is true for new clusters.

2023-10-04 04:35 UTC, ddhodge commented on docs/content/preview/reference/configuration/yb-tserver.md
> +--ycql_enable_packed_row support is currently in [Tech Preview](/preview/releases/versioning/#feature-availability).
```suggestion
YCQL packed row support is currently in [Tech Preview](/preview/releases/versioning/#feature-availability).
```

2023-10-06 18:11 UTC, ddhodge commented on docs/content/stable/architecture/docdb/persistence.md
> +The key-value pairs that are displayed in strike-through font are logically deleted. The preceding DocDB layout is not the physical layout by itself, as the writes happen in a log-structured manner.
```suggestion
The key-value pairs that are displayed in strike-through font are logically deleted. The preceding DocDB layout is not the physical layout, as the writes happen in a log-structured manner.
```

2023-10-06 18:12 UTC, ddhodge commented on docs/content/preview/architecture/docdb/persistence.md
> +The key-value pairs that are displayed in strike-through font are logically deleted. The preceding DocDB layout is not the physical layout by itself, as the writes happen in a log-structured manner.
```suggestion
The key-value pairs that are displayed in strike-through font are logically deleted. The preceding DocDB layout is not the physical layout, as the writes happen in a log-structured manner.
```

2023-10-06 18:12 UTC, ddhodge approved these changes

2023-10-10 15:54 UTC, rthallamko3 approved these changes

2023-10-10 16:43 UTC, merged