[docs] Back up YBA installer using yba_ctl
yugabyte/yugabyte-db pull request #19526
Opened 2023-10-13 16:29 UTC by aishwarya24

2023-10-23 22:47 UTC, ddhodge approved these changes
misc comments

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +You can use the YBA Installer [yba-ctl](../../install-yugabyte-platform/install-software/installer/#download-yba-installer) script which internally executes the `yb_platform_backup.sh` script to back
```suggestion
If you installed YBA using [YBA installer](../../install-yugabyte-platform/install-software/installer/), use the [yba-ctl](../../install-yugabyte-platform/install-software/installer/#download-yba-installer) CLI to back up and restore your YBA installation. The CLI executes the `yb_platform_backup.sh` script to back up an existing YugabyteDB Anywhere server and restore it, when needed, for disaster recovery or migrating to a new server.
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +## Back up YBA if installed using YBA Installer
```suggestion
## Back up YBA
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +## Restore YBA if installed using YBA Installer
```suggestion
## Restore YBA
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +1. Run the `yba-ctl` script using the `restoreBackup` command:
```suggestion
1. Run the `restoreBackup` command as follows:
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +    The `restoreBackup` command executes the `yb_platform_backup.sh` to restore from a previously taken backup of your YugabyteDB Anywhere instance. Executing this command requires that you specify t
```suggestion
    The `restoreBackup` command executes the `yb_platform_backup.sh` script to restore from a previously taken backup of your YugabyteDB Anywhere instance. Specify the `input_path` to the backup `.tar.gz` file as the only argument.
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +1. Run the `yba-ctl` script using the `createbackup` command, as follows:
```suggestion
1. Run the `createbackup` command, as follows:
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +    The `createBackup` command executes the `yb_platform_backup.sh` script to create a backup of your YugabyteDB Anywhere instance. Executing this command requires that you specify the `output_path`
```suggestion
    The `createBackup` command executes the `yb_platform_backup.sh` script to create a backup of your YugabyteDB Anywhere instance. Specify the `output_path` where you want the backup `.tar.gz` file to be stored.
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +Upon completion of the preceding steps, the restored YugabyteDB Anywhere is ready to continue managing your universes and clusters.
```suggestion
When finished, the restored YugabyteDB Anywhere is ready to continue managing your universes and clusters.
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +    ./yba-ctl.sh createBackup <output_path> [flags]
```suggestion
    yba-ctl createBackup <output_path> [flags]
```

2023-10-23 22:47 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +If you installed YugabyteDB Anywhere using [YBA installer](../../install-yugabyte-platform/install-software/installer/), perform the following steps:
```suggestion
To back up your YugabyteDB Anywhere installation, perform the following steps:
```

2023-10-24 14:53 UTC, chidmuthu commented
I think we should also add some examples of what flags are available (don't need all of them) and highlight they are 1) optional and 2) can be viewed by running createBackup --help

2023-10-25 23:24 UTC, aishwarya24 commented
> I think we should also add some examples of what flags are available (don't need all of them) and highlight they are 1) optional and 2) can be viewed by running createBackup --help

@chidmuthu - Added the flags description in a table. Can you PTAL?

2023-10-31 17:33 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/back-up-restore-installer.md
> +    yba-ctl createBackup <output_path> [flags]
Add sudo

2023-10-31 17:34 UTC, chidmuthu requested changes
We also need for 2.18, no?

2023-10-31 18:39 UTC, aishwarya24 commented
> We also need for 2.18, no?

Yes stable is 2.18. So, yes I have it included in stable.

2023-11-02 23:25 UTC, chidmuthu approved these changes

2023-11-03 01:19 UTC, merged