[docs][yba] Migrate YBA from Replicated
yugabyte/yugabyte-db pull request #20043
Opened 2023-11-28 05:05 UTC by ddhodge

Using YBA Installer to migrate installation from Replicated
PLAT-10754

@netlify /preview/yugabyte-platform/install-yugabyte-platform/

2023-12-12 19:08 UTC, shubin-yb requested changes

2023-12-13 15:18 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +1. If the new YBA installation is correct, finish the migration as follows:
@shubin-yb It says "At this point, if you find problems, you can revert to your Replicated installation..."

2023-12-13 18:54 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +1. If your Replicated installation is v2.18.5 or earlier, [upgrade your installation](../../../upgrade/upgrade-yp-replicated/) to v2.20.1.
cc @shubin-yb
Ya that makes it more complicated
"If your Replicated installation is v2.18.5 or earlier, or v2.20.0, upgrade..." - clear enough?

2023-12-13 20:25 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +1. If your Replicated installation is v2.18.5 or earlier, [upgrade your installation](../../../upgrade/upgrade-yp-replicated/) to v2.20.1.
Yes, I think that makes sense!

2023-12-13 20:25 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +1. [Remove the standby instances](../../administer-yugabyte-platform/high-availability/#remove-a-standby-instance).
Yes, they also have to delete the entire configuration, not just the instances.

2023-12-13 20:25 UTC, shubin-yb commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +1. If your Replicated installation is v2.18.5 or earlier, [upgrade your installation](../../../upgrade/upgrade-yp-replicated/) to v2.20.1.
I think this makes sense

2023-12-13 20:26 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +1. [Remove the standby instances](../../administer-yugabyte-platform/high-availability/#remove-a-standby-instance).
There's a `Delete Configuration` button in the top right of the Admin HA configuration section

2023-12-13 21:27 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +1. If the new YBA installation is correct, finish the migration as follows:
Note in intro above, and new section on HA below...

2023-12-13 21:34 UTC, ddhodge commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +1. If the new YBA installation is correct, finish the migration as follows:
OK added bit about not configuring HA before `finish`...

2023-12-18 23:03 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +
As a catchall let's highlight that failovers are NOT possible until after finalization  before we go into HTTP/HTTPS.

2023-12-19 04:56 UTC, shubin-yb approved these changes
LG, thanks for iterating on this!

2023-12-28 19:05 UTC, aishwarya24 approved these changes
perform the same changes to stable.

2023-12-28 19:05 UTC, aishwarya24 commented on docs/content/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
just minor that can be addressed later- the output of the status command is not rendered clearly : https://deploy-preview-20043--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/install-yugabyte-platform/install-software/installer/#service-management

2023-12-28 19:05 UTC, aishwarya24 commented on docs/content/preview/yugabyte-platform/upgrade/upgrade-yp-replicated.md
> +YugabyteDB Anywhere will end support for Replicated installation at the end of 2024. You can migrate existing Replicated YugabyteDB Anywhere installations using YBA Installer. See [Migrate from Repli
broken link.

2023-12-28 20:35 UTC, merged