[docs] added umask command to upgrade YBA steps
yugabyte/yugabyte-db pull request #21153
Opened 2024-02-22 18:32 UTC by aishwarya24

Slack request - https://yugabyte.slack.com/archives/CDQB8MEAU/p1708614538019359
Zendesk - https://yugabyte.zendesk.com/agent/tickets/8975

2024-02-23 21:29 UTC, chidmuthu requested changes
^

2024-02-23 21:46 UTC, aishwarya24 commented
> No, on versions <2.18.4.2 umask must be set to 022 before performing the install. Anything 2.18.4.2+ we don't have to worry about umask, YBA-installer handles it automatically.

Thought so. In that case, we don 't even need to mention it on the stable docs page as its addressing 2.20 series right? @chidmuthu

2024-02-23 21:52 UTC, chidmuthu commented
> > No, on versions <2.18.4.2 umask must be set to 022 before performing the install. Anything 2.18.4.2+ we don't have to worry about umask, YBA-installer handles it automatically.
> 
> Thought so. In that case, we don 't even need to mention it on the stable docs page as its addressing 2.20 series right? @chidmuthu

Yes, but on 2.18 docs page we should call out on YBA-installer YBA install page if they are installing < 2.18.4.2 the umask will need to be set to 022 before performing the install

2024-02-23 22:01 UTC, aishwarya24 commented
@chidmuthu - Cuurently , we don't have an YBA installer upgrade page for 2.18 - https://docs.yugabyte.com/v2.18/yugabyte-platform/upgrade/. So ill create a similar one and update this PR. Thanks for the clarification.

2024-02-23 22:03 UTC, chidmuthu commented
No this is not only for upgrades. It affects fresh install too. If they are doing upgrade they probably already set the umask (but it is not the worst to clarify on upgrades as umask should be set then as well)

2024-02-28 01:55 UTC, chidmuthu approved these changes

2024-02-28 21:27 UTC, ddhodge commented on docs/content/v2.18/yugabyte-platform/install-yugabyte-platform/install-software/installer.md
> +- Note that if you are trying to install YBA installer less than version 2.18.4.2, you need to set umask for the root user to 022.
```suggestion
- If you are installing a version earlier than v2.18.4.2, set umask for the root user to 022.
```

2024-02-28 21:28 UTC, ddhodge approved these changes

2024-02-28 21:59 UTC, merged