Add more information to user enforced consistency
yugabyte/yugabyte-db pull request #21457
Opened 2024-03-13 19:22 UTC by premkumr

- Added a Caution for the user to be wary of issues.
- Made a note on backfilling

2024-03-15 14:51 UTC, KavyaShivashankar requested changes
Index backfill does not automatically occur due the value set on this flag ```disable_index_backfill_for_non_txn_tables=true```.   Once the value of this flag is set to ```false```,  automatic backfill happens at the time of Index creation.  

 Backfill operation has to be manually initiated for index created during the time this flag had a value ```true```

2024-03-15 21:25 UTC, premkumr commented
@KavyaShivashankar  - please verify!

2024-03-18 19:52 UTC, aishwarya24 commented on docs/content/stable/api/ycql/ddl_create_index.md
> +When using an index without transactions enabled, it is the responsibility of the application to retry any insert/update/delete failures to make sure that the table and index are in sync. <br><br>Als
```suggestion
When using an index without transactions enabled, it is the responsibility of the application to retry any insert/update/delete failures to make sure that the table and index are in sync. 

Also, if the index is created after data has been added to the table, the index may **not** be backfilled automatically depending on the setting of the `disable_index_backfill_for_non_txn_tables` flag. If set to `true`, then it is the responsibility of the user to trigger a backfill using the [yb-admin backfill_indexes_for_table](../../../admin/yb-admin/#backfill-indexes-for-table) command, which will trigger the backfill after a small delay of about a minute. This delay is controlled by the `index_backfill_upperbound_for_user_enforced_txn_duration_ms` flag.
```

2024-03-20 20:46 UTC, ddhodge commented on docs/content/preview/api/ycql/ddl_create_index.md
>  ### User enforced consistency
```suggestion
### User-enforced consistency
```

2024-03-20 20:48 UTC, ddhodge commented on docs/content/stable/api/ycql/ddl_create_index.md
>  ### User enforced consistency
```suggestion
### User-enforced consistency
```

2024-03-20 20:48 UTC, ddhodge approved these changes

2024-03-21 02:26 UTC, merged