[doc][yba] Release management enhancement
yugabyte/yugabyte-db pull request #22173
Opened 2024-04-28 00:23 UTC by ddhodge

Release management updates
DOC-306

@netligy /preview/yugabyte-platform/manage-deployments/upgrade-software/

2024-04-29 20:30 UTC, hari90 requested changes

2024-04-29 20:30 UTC, hari90 commented on docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software.md
>  1. [Review major changes in previous YugabyteDB releases](../upgrade-software-prepare/). Depending on the upgrade you are planning, you may need to make changes to your automation or upgrade your Lin
```suggestion
1. [Prepare to upgrade a universe](../upgrade-software-prepare/). Depending on the upgrade you are planning, you may need to make changes to your automation or upgrade your Linux operating system.
```

2024-04-29 20:30 UTC, hari90 commented on docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software-install.md
> +If you have problems, you can [roll back](#roll-back-an-upgrade) any time.
```suggestion
If you have problems, you can [roll back](#roll-back-an-upgrade) during this time.
```

2024-04-29 20:30 UTC, hari90 commented on docs/content/preview/yugabyte-platform/manage-deployments/upgrade-software-install.md
> +If you aren't satisfied with an upgrade, you can roll back to the version that was previously installed. The process is similar to [performing an upgrade](#perform-the-upgrade).
The process is similar to

is this necessary?

2024-04-29 20:30 UTC, hari90 commented on docs/content/preview/yugabyte-platform/manage-deployments/ybdb-releases.md
> +Before you can upgrade your universe to a specific version of YugabyteDB, verify that the release is available and, if necessary, import the release into YugabyteDB Anywhere.
```suggestion
Before you can upgrade your universe to a specific version of YugabyteDB, verify that the release is available in YugabyteDB Anywhere and, if necessary, import it .
```

2024-04-29 20:30 UTC, hari90 commented on docs/content/preview/yugabyte-platform/manage-deployments/ybdb-releases.md
> +If a release that you want to install on a universe is not available, import it as follows:
```suggestion
If a release that you want to install or upgrade is not available, import it as follows:
```

2024-04-29 20:30 UTC, hari90 commented on docs/content/preview/yugabyte-platform/manage-deployments/ybdb-releases.md
> +    ![Import Release](/images/yp/import-releases-2024.png)
The image has a lot of white space. Can we trim it?

2024-04-30 16:59 UTC, hari90 approved these changes

2024-05-10 14:33 UTC, rajmaddy89 commented
We need to include the Best Practices from the doc: https://docs.google.com/document/d/1UvYk_dtIZKALteQSvpBuryrn2NyFYyD81yMzJxXdtVM/edit#heading=h.i1si75mqkqn6

2024-05-13 08:37 UTC, ddhodge commented on docs/content/preview/releases/yba-releases/_index.md
> +Note that you cannot deploy or upgrade a universe to a higher version of YugabyteDB than the version of YugabyteDB Anywhere. To upgrade a universe to a more recent version of YugabyteDB, you may firs
You can't use YBA to deploy versions of YugabyteDB that are newer than your YBA instance. To upgrade a universe to a more recent version of YugabyteDB, you may first have to upgrade YBA.

2024-05-29 14:35 UTC, aishwarya24 commented
Created a new PR - https://github.com/yugabyte/yugabyte-db/pull/22596

2024-05-29 14:35 UTC, closed without merging