[doc][yba] 2024.1 High availabiliy updates
yugabyte/yugabyte-db pull request #22186
Opened 2024-04-29 20:06 UTC by ddhodge

High availabiliy updates
DOC-270

@netlify /preview/yugabyte-platform/administer-yugabyte-platform/high-availability/

2024-04-29 20:48 UTC, aishwarya24 approved these changes
LGTM

2024-04-30 19:21 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
>  - A standby instance is completely passive while in standby mode and can't be used for managing or monitoring clusters until you manually promote it to active.
Standby can be used for monitoring Prometheus data so probably want to remove that word. It can't be used for any YBA actions though.

2024-04-30 19:31 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
We need new screenshots. Let me upload those to the google doc.

2024-04-30 19:33 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
> +After configuring a standby instance, you need to add it to the active instance. Note that standby instances and the active instance must use the same authentication key.
and the standby instance must already be configured.

2024-04-30 19:41 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
disable HA completely is a little ambiguous. Maybe delete the HA configuration and follow the setup instructions again.

2024-04-30 19:44 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
> +If you are promoting a YBA standby that is running version 2024.1.0 or later, while the old active instance is running a version earlier than 2024.1.0, see the [Limitations](#limitations).
Let's highlight that this should only be done in extreme scenarios and refer them back to where we talk about version mismatches and how active/standby should be on the same version and upgraded together. They will need to reach out to support

2024-04-30 19:45 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
> +If you are promoting a YBA standby that is running version 2024.1.0 or later, while the old active instance is running a version earlier than 2024.1.0, see the [Limitations](#limitations).
Oh I see you called that out in the Limitations, nevermind.

2024-04-30 19:46 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
> +The easiest way to determine the health of your HA configuration is to monitor the overall HA state on your active YBA instance. The overall HA state is computed from the individual instance states,
which can be viewed

2024-04-30 19:48 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
> +The easiest way to determine the health of your HA configuration is to monitor the overall HA state on your active YBA instance. The overall HA state is computed from the individual instance states,
And also highlight Global State is viewed on Replication Configuration tab, unlike the individual instance states.

2024-04-30 19:52 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
> +    This alert fires when backup to a particular standby has failed for a specified amount of time. The default is 15 minutes.
but can be configured by editing the HA Standby Sync alert policy.

2024-04-30 19:53 UTC, chidmuthu requested changes
Will also add updated screenshots to the Google Doc that you can use to update

2024-04-30 20:16 UTC, chidmuthu commented
> Will also add updated screenshots to the Google Doc that you can use to update

Actually my bad, I already did this. The first screen is just the same. I did add a screenshot to the verify validate page.

2024-05-06 18:04 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
>      If you can't identify the timestamp for whatever reason, you can provide a current timestamp to forcibly demote the instance. However, it will be harder to reestablish the HA connection as the ac
Remove this, they should always be able to retrieve the timestamp.

2024-05-06 18:09 UTC, chidmuthu commented on docs/content/preview/yugabyte-platform/administer-yugabyte-platform/high-availability.md
> +- On the active instance, navigate to **Admin > High Availability > Instance Configuration** and verify the time since last backup is within the replication frequency.
add for each individual standby

2024-05-06 18:19 UTC, chidmuthu commented
There are a couple new screenshots in the google doc (1 for the new failover dialog box and 1 for the monitoring screenshot). Once we add those I think we should be good!

2024-05-06 20:30 UTC, chidmuthu commented
Oh, let's also add section at the bottom linking to API Examples and point them to the Github notebook https://github.com/yugabyte/yugabyte-db/blob/master/managed/api-examples/python-simple/high-availability.ipynb

2024-05-20 16:30 UTC, chidmuthu approved these changes

2024-05-29 04:54 UTC, closed without merging