[doc][ybm] Changes for pricing plans #20900
yugabyte/yugabyte-db pull request #22588
Opened 2024-05-29 06:02 UTC by ddhodge

Changes for pricing plans

@netlify /preview/yugabyte-cloud/

2024-06-21 18:03 UTC, aishwarya24 reviewed
some comments

2024-06-21 18:03 UTC, aishwarya24 commented on docs/content/v2.20/explore/fault-tolerance/handling-region-failures.md
> +{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in YugabyteDB Managed. {{</note>}}
```suggestion
{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in YugabyteDB Aeon. {{</note>}}
```

2024-06-21 18:03 UTC, aishwarya24 commented on docs/content/v2.20/explore/fault-tolerance/handling-region-failures.md
> +{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in YugabyteDB Managed. {{</note>}}
```suggestion
{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in YugabyteDB Managed. {{</note>}}
```
```suggestion
{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in YugabyteDB Aeon. {{</note>}}
```

2024-06-21 18:03 UTC, aishwarya24 commented on docs/content/v2.20/explore/fault-tolerance/handling-region-failures.md
> +{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in YugabyteDB Managed. {{</note>}}
```suggestion
{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in YugabyteDB Aeon. {{</note>}}
```

2024-06-21 18:03 UTC, aishwarya24 commented on docs/content/v2.20/explore/fault-tolerance/handling-node-upgrades.md
> +{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in [YugabyteDB Managed](/preview/yugabyte-cloud/) for an upgrade. {{</note>}}
```suggestion
{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to stop a node in [YugabyteDB Aeon](/preview/yugabyte-cloud/) for an upgrade. {{</note>}}
```

2024-06-21 18:03 UTC, aishwarya24 commented on docs/content/v2.20/explore/fault-tolerance/handling-node-upgrades.md
> +{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to restart a node in [YugabyteDB Managed](/preview/yugabyte-cloud/).  {{</note>}}
```suggestion
{{<note>}} Reach out [YugabyteDB support](https://support.yugabyte.com) to restart a node in [YugabyteDB Aeon](/preview/yugabyte-cloud/).  {{</note>}}
```

2024-06-23 11:58 UTC, rangasayeelc-yb approved these changes
eyeballed the changes across 20-25 files. I can't seem to figure out how to effectively use additional tooling to preview each page.

2024-06-23 11:58 UTC, rangasayeelc-yb commented on docs/content/preview/admin/ysqlsh-meta-commands.md
> -For security reasons, the YugabyteDB Managed cloud shell only has access to a subset of meta-commands. With the exception of read-only access to the `/share` directory to load the sample datasets, co
'Similarly' -> 'Similar to psql'

2024-06-23 11:59 UTC, rangasayeelc-yb reviewed
@ddhodge these are the naming changes. Where can I find the pricing plan updates?

2024-06-23 12:22 UTC, rangasayeelc-yb requested changes
@ddhodge found the pricing changes, made a few suggestions on the same.
Renaming changes look good - eyeballed about 25 files but did not check everything

2024-06-23 12:22 UTC, rangasayeelc-yb commented on docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-costs.md
> +The following calculations reflect the Standard plan rate card.
@ddhodge can you please link to the pricing page from here ('Standard plan rate card')? Or add a link for more information, for example, 'For more information on plan based pricing, see <yugabyte.com/pricing>'

2024-06-23 12:22 UTC, rangasayeelc-yb commented on docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-costs.md
> +headcontent: Plan-based cluster pricing
@ddhodge pricing is for the account, not per cluster or cluster based. Can we remove this sub-heading?

2024-06-23 12:22 UTC, rangasayeelc-yb commented on docs/content/preview/yugabyte-cloud/cloud-admin/cloud-billing-costs.md
> +      Plan Pricing
rename to 'Plan based Pricing'

2024-06-24 15:01 UTC, merged