[DOC-441] Examples for pg_cron extension
yugabyte/yugabyte-db pull request #23484
Opened 2024-08-13 15:36 UTC by aishwarya24

@netlify /preview/explore/ysql-language-features/pg-extensions/extension-pgcron/#examples

2024-08-14 15:02 UTC, hari90 requested changes

2024-08-14 15:02 UTC, hari90 commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +
Pg cron readme and Aurora docs have examples of this too

2024-08-14 15:02 UTC, hari90 commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +### Archive old data
With partman we will just move the data to a different partion. So let's just use the example of deleting old data here.
Moving can be an expensive operation.

2024-08-20 20:05 UTC, hari90 commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +SELECT * FROM pg_stat_statements ORDER BY total_time DESC LIMIT 10;
```suggestion
INSERT INTO slow_queries SELECT * FROM pg_stat_statements ORDER BY total_time DESC LIMIT 10;
```

2024-08-20 20:06 UTC, hari90 commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +### Best practices
Lets make this a ## heading and move it before Examples

2024-08-20 20:08 UTC, hari90 commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +    If you do not want to use `cron.job_run_details` at all, then you can add `cron.log_run = off` to `postgresql.conf`.
Lets remove this. This does not work in yb

2024-08-20 20:09 UTC, hari90 commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +#### Create a cleanup function
I dont think we need this. It looks very similar to the previous one.

2024-08-24 05:20 UTC, ddhodge approved these changes
misc comments

2024-08-24 05:20 UTC, ddhodge commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +As a best practice, you can set up a periodic cleanup task for the `cron.job_run_details` table using the `pg_cron` extension ensuring old data doesn't accumulate and affect database performance. The
```suggestion
The `cron.job_run_details` table is part of the `pg_cron` extension in PostgreSQL. This table keeps a record of the execution details of the scheduled cron jobs. It logs information about each cron job run, including its start and end time, status, and any exit messages or errors that occurred during the execution. The records in `cron.job_run_details` are not cleaned automatically, so in scenarios where you have jobs that run every few seconds, set up a periodic cleanup task for the table using `pg_cron` to ensure old data doesn't accumulate and affect database performance.
```

2024-08-24 05:20 UTC, ddhodge commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +1. You can view the status of running and recently completed job runs in the `cron.job_run_details` table using the following command:
```suggestion
1. You can view the status of running and recently completed jobs in the `cron.job_run_details` table using the following command:
```

2024-08-24 05:20 UTC, ddhodge commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +1. The records in `cron.job_run_details` are not cleaned automatically. So in scenarios when you have jobs that run every few seconds, it can be a good idea to clean up regularly, which can easily be
```suggestion
1. Create a periodoc cleaning task for the table using `pg_cron` as follows:
```

2024-08-24 05:20 UTC, ddhodge commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +This example schedules a job to refresh the `your_materialized_view` every hour.
```suggestion
The following example schedules a job to refresh the `your_materialized_view` every hour.
```

2024-08-24 05:20 UTC, ddhodge commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +This example schedules a job to delete logs older than 30 days every day at 2AM.
```suggestion
The following example schedules a job to delete logs older than 30 days every day at 2AM.
```

2024-08-27 19:56 UTC, aishwarya24 commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +
Skip the example ? Or just the second part ? @hari90

2024-08-28 20:18 UTC, hari90 commented on docs/content/preview/explore/ysql-language-features/pg-extensions/extension-pgcron.md
> +
On second thought it is useful. Lets maybe move it out as its own tip instead of putting it in the cleanup section?

2024-09-06 13:20 UTC, merged