[doc][yba] Export audit logs
yugabyte/yugabyte-db pull request #23605
Opened 2024-08-23 15:25 UTC by ddhodge

Export audit logs
PLAT-14051

@netlify /preview/yugabyte-platform/alerts-monitoring/universe-logging/

2024-08-27 14:16 UTC, aishwarya24 reviewed
some comments.

2024-08-27 14:16 UTC, aishwarya24 commented on docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
> +Export configuration is {{<badge/ea>}}. To enable export configuration management, set the **Enable DB Audit Logging** Global Configuration option (config key `yb.universe.audit_logging_enabled`) to
```suggestion
Export configuration is {{<badge/ea>}}. To enable export configuration management, set the **Enable DB Audit Logging** Global Configuration option (config key `yb.universe.audit_logging_enabled`) to true. Refer to [Manage runtime configuration settings](../../administer-yugabyte-platform/manage-runtime-config/). Note that only a Super Admin user can modify Global configuration settings. The flag can't be turned off if audit logging is enabled on a universe.
```

2024-08-27 14:16 UTC, aishwarya24 commented on docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
> +Create and manage export configurations on the **Integrations > Log** page.
I can't see "Logs" on portal.dev. Assuming thats expected as its on 2.23.x

2024-08-27 14:16 UTC, aishwarya24 commented on docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
> +![Export configurations](/images/yp/export-configurations.png)
Image is missing.

2024-08-30 05:41 UTC, Sahith02 reviewed
Added a few comments, rest looks good to me. Please get it reviewed by the PM also once (Ranga).

2024-08-30 05:41 UTC, Sahith02 commented on docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
> +1. Use the configuration to export data from a universe. While the connection is active, metrics or logs are automatically streamed to the tool.
Change "data" to "audit logs"?
Change "metrics or logs" to just "logs"

2024-08-30 05:41 UTC, Sahith02 commented on docs/content/preview/yugabyte-platform/alerts-monitoring/anywhere-export-configuration.md
> +- Access Key ID and Secret Access Key for the AWS Service Account
Should we mention the other requirements such as Log group, Log stream, and region here?

2024-08-30 05:41 UTC, Sahith02 commented on docs/content/preview/yugabyte-platform/alerts-monitoring/universe-logging.md
> +| pgaudit.log_level | Sets the [severity level](https://www.postgresql.org/docs/11/runtime-config-logging.html#RUNTIME-CONFIG-SEVERITY-LEVELS) of logs written to clients when `pgaudit.log_client` is
Also need to mention setting the log_min_messages gflag for this pgaudit.log_level param to work properly. This is mentioned in the doc content file.

2024-09-01 17:30 UTC, rangasayeelc-yb requested changes

2024-09-01 17:30 UTC, rangasayeelc-yb commented on docs/content/preview/yugabyte-platform/alerts-monitoring/universe-logging.md
> +title: Export PostgreSQL logs from YugabyteDB Anywhere universes
"PostgreSQL logs" -> shouldn't we say YSQL audit logs? Same question for the subtitle here in YBM / Aeon https://deploy-preview-23605--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-cloud/cloud-monitor/logging-export/

2024-09-01 17:30 UTC, rangasayeelc-yb commented on docs/content/preview/yugabyte-platform/alerts-monitoring/universe-logging.md
> +The Audit log export feature is {{<badge/ea>}}. To enable the feature in YugabyteDB Anywhere, set the **Enable DB Audit Logging** Global Configuration option (config key `yb.universe.audit_logging_en
@Sahith02 if the feature is behind a UI / API/ CLI feature flag, why do we need to keep it disabled this way as well?

2024-09-01 17:30 UTC, rangasayeelc-yb commented on docs/content/preview/yugabyte-platform/alerts-monitoring/universe-logging.md
> +- Log export uses a PostgreSQL extension and is only compatible with YSQL.
rephrase second limitation to, "Only YSQL database audit logs can be exported, not YCQL"

2024-09-01 17:30 UTC, rangasayeelc-yb commented on docs/content/preview/yugabyte-platform/alerts-monitoring/universe-logging.md
> +- There are also no alerts or metrics currently available for this feature.
I don't think we need to say this as it is orthogonal to log export

2024-09-01 17:30 UTC, rangasayeelc-yb commented on docs/content/preview/yugabyte-platform/alerts-monitoring/universe-logging.md
> +- Database audit logging. Using the [PostgreSQL Audit Extension](https://www.pgaudit.org/#) ([pgaudit](https://github.com/pgaudit/pgaudit/blob/1.3.2/README.md)), the audit log provides the exact data
@ddhodge @Sahith02 
do we need to mention the pgaudit version as users cannot change it and the supported logging parameters are documented in this article? what do we do for other extensions / plugins that we support?

2024-09-03 16:13 UTC, merged