[doc][xcluster][2024.1.2] Database level transactional xCluster
yugabyte/yugabyte-db pull request #23710
Opened 2024-08-29 03:26 UTC by ddhodge

Database-level setup of transactional xCluster replication

@netlify /preview/deploy/multi-dc/async-replication/async-replication-transactional/

2024-08-29 17:16 UTC, hari90 requested changes

2024-08-29 17:16 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
> +        create_xcluster_checkpoint <replication_group_id> <namespace_names>
Lets call it `comma_separated_namespace_names`

2024-08-29 17:16 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
> +
We still need to enable PITR the standby database. Same instructions from Manual mode can be copied here

2024-08-29 17:16 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
> +
Enable PITR on standby database

2024-08-29 17:16 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
> +When performing any DDL operation on databases using database-level transactional xCluster replication (such as creating, altering, or dropping tables or partitions), do the following:
```suggestion
When performing any DDL operation on databases using database-level transactional xCluster replication (such as creating, altering, or dropping tables, indexes or partitions), do the following:
```

2024-08-29 17:16 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
> +The xCluster configuration is updated automatically. You can insert data into the table as soon as it is created.
```suggestion
The xCluster configuration is updated automatically. You can insert data into the table as soon as it is created on Primary.
```

2024-08-29 17:16 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup.md
> +    <a href="../async-transactional-setup/" class="nav-link active">
Can we make DB level the default option?

2024-08-29 17:17 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
> +- [Database-level setup](../async-transactional-setup-dblevel/), providing operationally simpler setup and management of replication, as well as simpler steps for performing DDL changes.
@lingamsandeep I guess we are calling this GA?

2024-08-29 17:17 UTC, hari90 commented
All this is available in 2024.1 so you can make the changes to stable as well

2024-08-29 19:47 UTC, ddhodge commented on docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
@hari90 all of what...

2024-08-29 20:28 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
Comment moved around.  xCluster role is no longer exists, so you can remove it.

2024-08-29 20:48 UTC, ddhodge commented
> All this is available in 2024.1 so you can make the changes to stable as well

Will port changes after getting all comments taken care of

2024-08-29 23:27 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-replication-transactional.md
> +- [Semi-automatic setup](../async-transactional-setup-dblevel/), providing operationally simpler setup and management of replication, as well as simpler steps for performing DDL changes.
```suggestion
- [Manual mode](../async-transactional-setup/).
- [Semi-automatic mode](../async-transactional-setup-dblevel/), providing operationally simpler setup and management of replication, as well as simpler steps for performing DDL changes.
```

2024-08-30 16:05 UTC, hari90 commented on docs/content/preview/deploy/multi-dc/async-replication/async-transactional-setup-dblevel.md
> +Semi-automatic setup of transactional xCluster replication simplifies the operational complexity of managing replication and making DDL changes.
I see 6 more references to `Semi-automatic setup`. Can we rename them all to `Semi-automatic mode`?

2024-08-30 19:31 UTC, hari90 approved these changes

2024-08-30 19:31 UTC, hari90 commented
LGTM. Thank you!

2024-09-03 15:25 UTC, merged