[DOC-523]: Changes for new edit universe changes
yugabyte/yugabyte-db pull request #24598
Opened 2024-10-23 20:28 UTC by rajmaddy89

Description
--
Changes for new edit universe changes

2024-10-23 20:30 UTC, rajmaddy89 commented
Note: This PR will be closed and not merged as we do not have 2024.2 folder in docs.
Also I will add an image for FULL MOVE confirmation dialog as well

@iSignal : The editing of AWS Instance Profile ARN and Public IP Setting via UI is not supported. 
Should we still comment about the Instance Profile ARN and IP Setting because its supported via API.
Please clarify.

2024-10-28 23:35 UTC, iSignal commented on docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
> +- Replication Factor (RF) - RF increases are supported for both k8s and VM universes. While editing RF, the user can add new AZs but cannot change other universe settings such as instance type
Should we remove this part from the draft given we are not shipping this in 2024.2.0?

2024-10-28 23:35 UTC, iSignal commented on docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
> +The following changes in configurations will result in a full move
Minor: It might be easier to describe what ops support a smart (@ddhodge has such a PR) that to list the opposite.

2024-10-29 14:20 UTC, closed without merging

2024-10-29 14:27 UTC, yorq requested changes

2024-10-29 14:27 UTC, yorq commented on docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
> +- Storage Type
And what about 'EBS Type', 'Provisioned IOPS', 'Provisioned Throughput' ?

2024-10-29 14:27 UTC, yorq commented on docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
> -Note that you can't change the replication factor of a universe.
I guess we should keep this sentence but rewrite it as this affects only primary cluster

2024-10-29 14:27 UTC, yorq commented on docs/content/preview/yugabyte-platform/manage-deployments/edit-universe.md
> +- Instance type, Volume count and size - you can select instance types configured in the provider
Why are we mixing instance type and volume size/count here?