Fix division by zero error in selectivity calculation
yugabyte/yugabyte-db pull request #24610
Opened 2024-10-24 11:48 UTC by Saru2003

This PR addresses a bug that can result in a division by zero when calculating selectivity in yb_create_distinct_index_path.

This addresses issue [#24568](https://github.com/yugabyte/yugabyte-db/issues/24568) by enhancing the reliability of the selectivity computation.

Please review my implementation and provide feedback.

2024-10-24 11:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=24610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=24610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yugabyte/yugabyte-db?pullRequest=24610) it.</sub>

2024-10-29 10:57 UTC, Saru2003 commented
Hi @sushantrmishra and @pao214,

I wanted to check in on the status of my pull request as Hacktoberfest is ending soon, and I’m hoping to get this contribution reviewed in time. Could you please let me know if there’s anything I need to adjust or if the PR could be approved as it is?

Thanks for your time and consideration!

2024-10-29 20:55 UTC, pao214 requested changes

2024-10-29 20:55 UTC, pao214 commented
> Hi @sushantrmishra and @pao214,
> 
> I wanted to check in on the status of my pull request as Hacktoberfest is ending soon, and I’m hoping to get this contribution reviewed in time. Could you please let me know if there’s anything I need to adjust or if the PR could be approved as it is?

Hey, I forgot to submit my review comment. Please take a look.

2024-10-30 07:04 UTC, Saru2003 commented on src/postgres/src/backend/optimizer/util/pathnode.c
> -	selectivity = ((Cost) numDistinctRows) / ((Cost) pathnode->path.rows);
I have applied the suggested changes. Kindly review my implementation and provide feedback.

2024-10-31 02:42 UTC, merged

2024-10-31 04:56 UTC, Saru2003 commented
@pao214 thanks for accepting the PR. Can you please add "hacktoberfest-accepted" label? It would mean a lot. 

Thanks for considering.

2024-10-31 16:35 UTC, Saru2003 commented
Hi @pao214, just wanted to follow up on my request. If you’re able to add the "hacktoberfest-accepted" label to my PR, I’d really appreciate it as it would help me complete my Hacktoberfest goal. Thank you again for your support!

2024-10-31 18:21 UTC, pao214 commented
We do not have such a label. Also, hacktoberfest-accepted label is only used for cases where the PR is not merged. This is clearly not that scenario.

2024-10-31 18:23 UTC, pao214 commented
Hi, we do not have a hacktoberfest-accepted label.

cc @sushantrmishra