[DOC-539 ]Added colocated tables with tablespaces
yugabyte/yugabyte-db pull request #24811
Opened 2024-11-06 16:23 UTC by aishwarya24

@netlify /v2024.2/explore/colocation/#colocated-tables-with-tablespaces

Note to self - Move the backup section to back up and restore after confirmation.

2024-11-17 17:40 UTC, ddhodge commented on docs/content/v2024.2/explore/colocation.md
> +- With `--use_tablespaces` option in [ysql_dump](../../admin/ysql-dump/). Using this option during backup and restore includes tablespace information. The restored database requires the target univer
We should add --use_tablespaces to ysql_dump docs at some point

2024-11-17 17:40 UTC, ddhodge approved these changes

2024-11-17 17:42 UTC, ddhodge commented
Some variation of "With the introduction of [tablespaces](../going-beyond-sql/tablespaces/) support for colocated tables {{<tags/feature/ea>}}, you can assign tablespaces to their colocated tables, bridging the gap between regional data distribution and performance demands. This development eliminates the need for trade-offs, allowing organizations to adhere to compliance requirements while benefiting from the efficiency of colocated tables and relations. By ensuring all colocated tables in a tablespace reside in the same tablet, this feature optimizes both data management and operational efficiency." would be suitable for RN highlights

2024-11-19 15:59 UTC, utkarsh-um-yb requested changes
I have made some additions to the original doc provided to you https://docs.google.com/document/d/1-iCCndnkLbaiftqMlp121i0wsK6ZndIruCO0H3P0PoU/edit, Have highlighted the changes Can you please accommodate  this changes too, thanks!

Also please add @suranjan  to this review as well.

2024-11-19 16:08 UTC, utkarsh-um-yb commented on docs/content/v2024.2/explore/colocation.md
> +Use the same syntax to create indexes and materialized views in a tablespace as follows:
```suggestion
Use the same syntax to create colocated indexes and materialized views in a tablespace as follows:
```

2024-11-19 16:08 UTC, utkarsh-um-yb commented on docs/content/v2024.2/explore/colocation.md
> +```
Please remove the oid column. The oid column shows up only in pg15, in 2024.2 it won't be there. Sorry this was a miss from my side, in the original doc.

2024-11-19 16:08 UTC, utkarsh-um-yb commented on docs/content/v2024.2/explore/colocation.md
> +The `oid` and `grpname` columns represent the tablegroup's OID and name, respectively. The `grptablespace` column shows the OID of the associated tablespace.
remove the `oid` description from here also.

2024-11-20 01:55 UTC, ddhodge commented on docs/content/v2024.2/explore/colocation.md
> +      Same `Group Name` indicates the colocated entities, and each tablegroup belongs to a different tablespace, as evident from the `grptablespace` column from the following table.
```suggestion
    The Group Name column shows which entities are colocated.
      
     Each tablegroup belongs to a different tablespace, as shown in the grptablespace column in the following table.
```

2024-11-20 01:56 UTC, ddhodge commented on docs/content/v2024.2/explore/colocation.md
> +      The same information after backup or restore without the `--use_tablespaces` option would look like the following:
```suggestion
      The same information after backup or restore without the `--use_tablespaces` option looks like the following:
```

2024-11-20 01:57 UTC, ddhodge commented on docs/content/v2024.2/explore/colocation.md
> +      As evident from the above table, the colocation property is still maintained after the backup or restore. But all these tables now reside in the same tablespace which is the default one, as per
```suggestion
    The colocation property is still maintained after the backup or restore. But all the tables now reside in the same tablespace (the default one):
```

2024-11-20 03:30 UTC, utkarsh-um-yb commented on docs/content/v2024.2/explore/colocation.md
> +The `oid` and `grpname` columns represent the tablegroup's OID and name, respectively. The `grptablespace` column shows the OID of the associated tablespace.
yes we can include that

2024-11-25 18:59 UTC, merged