[DOC-522] Rolling operations in batches and YBA compatibility for 2024.2
yugabyte/yugabyte-db pull request #24903
Opened 2024-11-13 20:25 UTC by aishwarya24

@netlify /v2024.2/yugabyte-platform/manage-deployments/edit-config-flags/#rolling-restart-in-batches

2024-11-15 10:27 UTC, yorq requested changes
Shouldn't we mention that this functionality is also available for other upgrades (but only by using runtime config)?

2024-11-18 10:30 UTC, yorq commented
@rajmaddy89 Yes, but I think it is ok not to mention it in docs

2024-11-18 10:30 UTC, yorq approved these changes
LGTM

2024-11-18 18:58 UTC, ddhodge reviewed
made some changes

2024-11-18 19:18 UTC, aishwarya24 commented on docs/content/v2024.2/yugabyte-platform/manage-deployments/edit-config-flags.md
> +YugabyteDB Anywhere allows processing multiple nodes simultaneously within each availability zone during rolling operations. YBA supports this rolling batch feature which is currently {{<tags/feature
cc @yorq @rajmaddy89

2024-11-22 14:43 UTC, yorq commented on docs/content/v2024.2/yugabyte-platform/manage-deployments/edit-config-flags.md
> +YugabyteDB Anywhere allows processing multiple nodes simultaneously within each availability zone during rolling operations. YBA supports this rolling batch feature which is currently {{<tags/feature
@ddhodge Then it depends on whether we apply upgrade on the whole node or on the process.
If the whole node (for ex ResizeNode) - we process this node one at a time
If we apply to process (GFlags upgrade) - then we process master on this node and later when all masters are processed we split tservers to batches

2024-11-25 16:25 UTC, merged