[doc][yba][2024.2][DOC-512] Group mapping to custom roles
yugabyte/yugabyte-db pull request #24935
Opened 2024-11-15 18:01 UTC by ddhodge

Group mapping to custom roles

@netlify /v2024.2/yugabyte-platform/administer-yugabyte-platform/oidc-authentication/

2024-11-22 13:06 UTC, asharma-yb commented on docs/content/v2024.2/yugabyte-platform/administer-yugabyte-platform/ldap-authentication.md
>1. Click **Create Mappings** (or, if you have existing mappings, **Edit**) to display the **Create Mapping** dialog.

This is now incorrect. From 2024.2 all group mappings, either builtin or custom will be done on the groups tab. 
This applies to both OIDC and LDAP.

2024-11-22 13:23 UTC, asharma-yb requested changes
Maybe we should also attach images of the groups tab since its a new addition with this release. 
The images present in the doc template can be used.

2024-11-22 13:23 UTC, asharma-yb commented on docs/content/v2024.2/yugabyte-platform/administer-yugabyte-platform/oidc-authentication.md
Also worth mentioning here that for every user (except SuperAdmin), the role determined via group mapping will override any role assigned previously.

2024-11-25 19:15 UTC, aishwarya24 approved these changes
LGTM

2024-11-25 20:10 UTC, merged