[#6320] Platform: Create Universe does not validate encryption-at-rest
yugabyte/yugabyte-db pull request #6950
Opened 2021-01-21 09:23 UTC by gaurav061

2021-01-21 09:24 UTC, gaurav061 commented
Fix: Dummy option had value as 0 which was causing this issue. PTAL

2021-01-21 09:26 UTC, jaydeepkumara approved these changes

2021-01-21 20:01 UTC, daniel-yb requested changes
Please add validation to the UniverseController that the kms config UUID passed in as part of the API payload is valid and corresponds to an existing KmsConfig model in the DB.

We need more than just UI validation since it's possible a customer may interact with the platform through API as opposed to UI.

2021-01-25 06:45 UTC, gaurav061 commented
@daniel-yb  We have a separate backend ticket to address this issue.https://github.com/yugabyte/yugabyte-db/issues/6862

2021-01-25 21:10 UTC, sshev approved these changes

2021-01-27 09:48 UTC, merged