[#7024] Platform: Fixed edit number of nodes in AZ section
yugabyte/yugabyte-db pull request #7029
Opened 2021-01-29 09:05 UTC by gaurav061

2021-01-29 09:07 UTC, gaurav061 commented
Fix: currentPlacementStatus prop was null initially when we land to edit universe page, so in mounting lifecycle i fetched this info if it is undefined or null.
Please add your comments

2021-02-02 07:15 UTC, sshev requested changes
Before https://github.com/yugabyte/yugabyte-db/commit/ad3a72ae2f48f5f9641305bc565e1345169903a1 commit the `currentPlacementStatus` prop was filled here https://github.com/yugabyte/yugabyte-db/blob/0857a10eed13435447efd21f651368f9b84dd028/managed/ui/src/components/universes/UniverseForm/AZSelectorTable.js#L469
Now this never happens due to extra conditions added at ClusterFields component:
`{placementStatusOnprem  || regionAndProviderDefined && azSelectorTable}`

This seems to be the real root cause, so let's investigate in that direction pls.

2021-02-05 12:03 UTC, gaurav061 commented
After adding the above condition `{placementStatusOnprem` || regionAndProviderDefined && azSelectorTable}` AzSelector component is being rendered with this `_.isEqual(universeConfigTemplate, this.props.universe.universeConfigTemplate)` as true and thus it is blocking this `this.props.setPlacementStatus(placementStatusObject); `  So, we need this call to be made in `UNSAFE_componentWillMount` lifecycle for 1st time rendering for subsequent rending the call will be made from `UNSAFE_componentWillReceiveProps` lifecycle. 
Please add to it.

2021-02-17 06:03 UTC, sshev approved these changes

2021-02-19 12:40 UTC, merged