[#6784] ysql: use all rather than 0.0.0.0/0, ::0/0 in hba conf
yugabyte/yugabyte-db pull request #7046
Opened 2021-02-01 03:54 UTC by pratikSethi

Replaced the occurrences of 0.0.0.0/0 and ::0/0 for ipv4 and ipv6 addressing with **all** in hba.conf

2021-02-01 03:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=7046) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yugabyte/yugabyte-db?pullRequest=7046) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yugabyte/yugabyte-db?pullRequest=7046) it.</sub>

2021-02-04 07:08 UTC, iSignal requested changes

2021-02-04 07:08 UTC, iSignal commented on src/yb/yql/pgwrapper/pg_wrapper.cc
> +    lines.push_back("host all all all trust");
we don't need both lines now

2021-02-04 07:08 UTC, iSignal commented on src/yb/yql/pgwrapper/pg_wrapper.cc
> +    lines.push_back(Format("$0 all all all $1", host_type, auth_method));
we don't need both lines now

2021-02-05 23:29 UTC, pratikSethi commented on src/yb/yql/pgwrapper/pg_wrapper.cc
> +    lines.push_back("host all all all trust");
You are right, I have updated my PR.

2021-02-05 23:30 UTC, pratikSethi commented on src/yb/yql/pgwrapper/pg_wrapper.cc
> +    lines.push_back(Format("$0 all all all $1", host_type, auth_method));
Change incorporated, thanks!

2021-02-11 23:03 UTC, iSignal approved these changes

2021-02-11 23:58 UTC, merged