[#5594] Platform:Handle invalid certs/keys correctly.
yugabyte/yugabyte-db pull request #7168
Opened 2021-02-08 20:50 UTC by jitendra-12113

**Heading:**
[5594][Platform] Handle invalid certs/keys correctly
**Description:**
We wanted to verify the cert at upload time itself.
**Testing:**
When we try to upload selfSigned cert, we were able to upload any
garbage files. Now with this fix, we have handled this scenrio. User
won't be able to upload garbage file. Incase of self signed cert upload
workflow, We are matching the modulus of
cert RSA Public key with the modulus of its private key if its matched
then it means certs are valid otheriwse Invalid.
For CA Cert, we are just validating the Cert format.
Added the unit Tests as well.

2021-02-10 11:14 UTC, Arnav15 requested changes
Looks good overall. Just few minor comments.
1) Add a unit test for a bad cert case as well.
2) Revert the submodule changes. You can do so by running `git submodule update --init --recursive`

2021-02-10 11:14 UTC, Arnav15 commented on managed/src/main/java/com/yugabyte/yw/common/CertificateHelper.java
> +  public static void saveCertContent(X509Certificate cert, String certPath) {
Rename similar to `writeKeyFileContentToKeyPath`

2021-02-10 11:15 UTC, Arnav15 commented
Also, can you update the description a little more. Exactly mention on how we are solving the issue and what all changes are made as part of this PR. And add the output of `sbt test`

2021-02-17 11:32 UTC, jitendra-12113 commented
Created separated PR for this:
https://github.com/yugabyte/yugabyte-db/pull/7264

2021-02-17 11:32 UTC, closed without merging