Ignore docs changes for yb-ctl workflow
yugabyte/yugabyte-db pull request #7388
Opened 2021-02-26 00:55 UTC by iSignal

yb-ctl workflow was being run for updates to the docs pages for it.

2021-02-26 01:37 UTC, polarweasel requested changes
In order to test that the ignore is working, I suggest making a change to `docs/content/latest/admin/yb-ctl.md` to make sure it doesn't trigger the CTL checks.

Deleting line 18 (one of two blank lines in a row) would be a great change, since it should be deleted anyway. :)

2021-06-04 23:46 UTC, polarweasel commented on .github/workflows/yb-ctl-test.yml
> +       - 'docs/**'
Need to adjust the syntax. Can't have `paths` and `paths-ignore` together.
```suggestion
      - '**/yb-ctl*'
      - '!docs/**'
```

2021-06-04 23:47 UTC, polarweasel commented on .github/workflows/yb-ctl-test.yml
> +       - 'docs/**'
Same as previous...
```suggestion
      - '**/yb-ctl*'
      - '!docs/**'
```

2021-06-04 23:48 UTC, polarweasel commented on .github/workflows/yb-ctl-test.yml
>        - '**/yb-ctl*'
Same as previous...
```suggestion
      - '**/yb-ctl*'
      - '!docs/**'
```

2021-06-04 23:48 UTC, polarweasel commented on .github/workflows/yb-ctl-test.yml
> +       - 'docs/**'
```suggestion
```

2021-07-02 17:37 UTC, polarweasel approved these changes
This looks good to me, but I made the last change here, so @iSignal please take a look and merge if it's good with you?

2021-07-27 00:54 UTC, iSignal commented
looks good, thanks for fixing it.

2021-07-27 00:54 UTC, merged