[#WIP] [Platform] Instance Type controller error handling.
yugabyte/yugabyte-db pull request #8122
Opened 2021-04-22 18:30 UTC by jitendra-12113

**Description:**
Use the new global exception handling in the Instance Type controller.

Test Plan:

Its mostly refactor. Unit tests are updated.
Run server and test basic operations.

2021-04-26 18:03 UTC, sb-yb requested changes

2021-04-26 21:37 UTC, sb-yb commented
Add [API] to subject

2021-04-27 06:07 UTC, jitendra-12113 commented on managed/src/main/java/com/yugabyte/yw/controllers/InstanceTypeController.java
> +      throw new YWServiceException(BAD_REQUEST, formData.errorsAsJson());
Yeah correct. Thanks for catching this.

2021-04-27 07:47 UTC, jitendra-12113 commented on managed/src/main/java/com/yugabyte/yw/controllers/InstanceTypeController.java
>      } catch (Exception e) {
How about logging the exception that will also be gone post removal of try catch. 
 
 Though I removed them just thought to highlight. Thanks!

2021-04-29 08:21 UTC, sb-yb commented on managed/src/main/java/com/yugabyte/yw/controllers/InstanceTypeController.java
>      } catch (Exception e) {
It will get logged at top level handler.

2021-04-29 08:22 UTC, sb-yb approved these changes
Thanks for making the changes.
This looks good now!

2021-04-29 18:35 UTC, merged