Docs changes for Geo-Distributed Placement
yugabyte/yugabyte-db pull request #9027
Opened 2021-06-22 17:27 UTC by deeps1991

This patch contains the following changes:
(i) Edit the images for the Tablespaces section to use the name
'multi_region_tablespace' rather than 'us_multi_region_tablespace'
as the tablespaces span multiple countries
(ii) Add a new command to yb-admin page to document the command
modify_table_placement_info
(iii) Edit a bug in Row Level Geo Partitioning page wherein a
 DEFAULT partition is created, and then a new partition is created.
We should not list this here as in some cases we can't create a new
partition if a default partition is present.
(iv) Add details about the above limitation to the section on
Table Partitioning.

2021-06-22 18:10 UTC, lizayugabyte reviewed
LGTM

2021-06-22 18:10 UTC, lizayugabyte commented on docs/content/latest/admin/yb-admin.md
> +* table_id: The unique uuid associated with the table whose placement policy is being  changed.
Extra space in "being  changed"

2021-06-22 18:51 UTC, deeps1991 commented
Added @rahuldesirazu and @bmatican mainly for the review of the yb-admin page. I've tagged this as WIP mainly to know if putting this command in the Table commands in yb-admin page looks ok.
Also wanted to ask if I should add any further details to the description of "placement_id"

2021-06-22 22:02 UTC, polarweasel requested changes
Left some changes as suggestions you can batch up, and also a couple of other comments

2021-06-22 22:02 UTC, polarweasel commented on docs/content/latest/explore/ysql-language-features/partitions.md
> +you can do so by adding a default partition in the following manner:
```suggestion
To create a new partition that contains only the rows that don't match the specified partitions, add a default partition as follows:
```

2021-06-24 22:56 UTC, deeps1991 commented on docs/content/latest/admin/yb-admin.md
> +    modify_table_placement_info tableid.<tableid> <placement_info> <replication_factor> \
Yes, that is the syntax... Here is an example run:

./yb-admin modify_table_placement_info tableid.77d9bfeea4fe4578a6dc8bf4529cb51e aws.us-west-2.us-west-2a0 3

2021-06-24 23:12 UTC, deeps1991 commented
Thanks for the quick reviews @lizayugabyte and @polarweasel! Addressed your comments above.

2021-07-07 22:50 UTC, rahuldesirazu approved these changes

2021-07-08 19:40 UTC, merged