[docs] PR for Document Sequelize in Integrations (Doc9383)
yugabyte/yugabyte-db pull request #9744
Opened 2021-08-16 21:51 UTC by lizayugabyte

2021-08-17 09:51 UTC, sanyamsinghal requested changes
Suggested some changes. Other than that it LGTM

2021-08-17 15:28 UTC, lizayugabyte commented on docs/content/latest/integrations/sequelize.md
> +This document describes how to use [Sequelize](https://sequelize.org/) with YugabyteDB to enable promise-based Node.js object-relational mapping (ORM).
Changed

2021-08-17 16:07 UTC, lizayugabyte commented on docs/content/latest/integrations/sequelize.md
> +
Added

2021-08-17 16:08 UTC, lizayugabyte commented on docs/content/latest/integrations/sequelize.md
> +## Limitations
Deleted section

2021-08-18 04:39 UTC, sanyamsinghal approved these changes
LGTM

2021-08-18 14:39 UTC, merged