[docs] update pgexercises page
yugabyte/yugabyte-db pull request #9791
Opened 2021-08-20 16:24 UTC by ddhodge

Remove reference to a Guthub issue that has been fixed

2021-08-20 21:41 UTC, polarweasel requested changes

2021-08-20 21:41 UTC, polarweasel commented on docs/content/latest/sample-data/pgexercises.md
> +```output
Line 81 is actually part of the output :)
````suggestion

```output
You are now connected to database "exercises" as user "yugabyte".
````

2021-08-20 21:41 UTC, polarweasel commented on docs/content/latest/sample-data/pgexercises.md
>    - YugabyteDB returns results with a sort order of strings different than in PostgreSQL due to [hash partitioning in YugabyteDB](../../architecture/docdb-sharding/).
Is there anything else we want to mention about the string sort order? (Like maybe an explanation?)

```suggestion
YugabyteDB returns the same results as expected based on the solutions on the PostgreSQL Exercises website, with one exception. In the ["Find telephone numbers with parentheses"](https://pgexercises.com/questions/string/reg.html) exercise, YugabyteDB returns results with a sort order of strings different than in PostgreSQL due to [hash partitioning in YugabyteDB](../../architecture/docdb-sharding/).
```

2021-08-22 21:47 UTC, ddhodge commented
Covered in #9530

2021-08-22 21:47 UTC, closed without merging