[docs] Add jsonb upsert
yugabyte/yugabyte-db pull request #9852
Opened 2021-08-27 18:36 UTC by ddhodge

Add jsonb upsert info for Spark connector (Java) #9805

https://deploy-preview-9852--infallible-bardeen-164bc9.netlify.app/latest/integrations/apache-spark/java/

2021-09-02 20:45 UTC, polarweasel requested changes

2021-09-02 20:45 UTC, polarweasel commented on docs/content/latest/integrations/apache-spark/java.md
> +For example, for `{"dl": null, "ul":"foo"}`, if `spark.cassandra.output.ignoreNulls` is specified, the value null would be omitted for field `dl` when writing (merging) into the corresponding JSONB c
```suggestion
For example, for `{"dl": null, "ul":"foo"}`, if `spark.cassandra.output.ignoreNulls` is specified, only the `ul` field gets written (merged) into the corresponding JSONB column, and the `ul` field is ignored.
```

2021-09-02 20:48 UTC, polarweasel commented
@nchandrappa please have a look at my comments...

2021-09-10 19:28 UTC, ddhodge commented on docs/content/latest/integrations/apache-spark/java.md
> +"dl":1122,"rsrp":["abc","rsrq":null,"sinr":"100.1"]
@nchandrappa

2021-09-13 16:54 UTC, nchandrappa commented on docs/content/latest/integrations/apache-spark/java.md
> +"dl":1122,"rsrp":["abc","rsrq":null,"sinr":"100.1"]
Yes, let's update the JSON snipped to a well-formed one Alex has provided above. Basically, snippet is trying to show quotes around json values.

2021-09-13 16:55 UTC, nchandrappa commented
other changes look good.

2021-09-14 20:56 UTC, polarweasel approved these changes
LGTM

2021-09-14 21:36 UTC, merged