[docs] Cloud docs (#9920)
yugabyte/yugabyte-db pull request #9964
Opened 2021-09-09 21:00 UTC by ddhodge

* [docs] Cloud docs

* various fixes

* fix quickstart duplicate data

* Misc edits and screenshots

* misc edits

* security page edits

* Chirag comments

* misc comments

* minore edits

* added YCQL Java app

* YCQL app edits

* misc edits

* updated examples

* cleanup and broken links

* hide some pages faq fixes

* minor fixes

* minor edit

* hide cluster costs

* updated screenshot

* add aliases

* updated security diagram

* added Rn

* release notes edits

* minor edits

* tweaked screenshots

* minor edits

* release note

* formatting

2021-09-09 23:12 UTC, polarweasel requested changes
Quick scrub over everything... One comment: careful with consistency in list items and run-in heads. Sometimes you use colons, sometimes not.

2021-09-09 23:12 UTC, polarweasel commented on docs/content/latest/yugabyte-cloud/cloud-clusters/overview.md
>  Metrics can be displayed over the past hour, 6 hours, 12 hours, 24 hours, or 7 days.
```suggestion
You can show metrics for the past hour, 6 hours, 12 hours, 24 hours, or 7 days.
```

2021-09-09 23:12 UTC, polarweasel commented on docs/content/latest/yugabyte-cloud/cloud-faq.md
> +Yugabyte Cloud clusters are accessed via [YSQL](../../api/ysql) and [YCQL](../../api/ycql) client APIs, and administered using the Yugabyte Cloud console.
```suggestion
You access your Yugabyte Cloud clusters via [YSQL](../../api/ysql) and [YCQL](../../api/ycql) client APIs, and administer your clusters using the Yugabyte Cloud console.
```

2021-09-09 23:12 UTC, polarweasel commented on docs/content/latest/yugabyte-cloud/cloud-quickstart.md
> +1. Choose the credentials you will use to connect to your YugabyteDB database in the cloud. You can choose the default set with a database user named "admin", or create your own.
```suggestion
1. Choose the credentials you'll use to connect to your YugabyteDB database in the cloud. You can choose the default set with a database user named "admin", or create your own.
```

2021-09-09 23:12 UTC, polarweasel commented on docs/content/latest/yugabyte-cloud/cloud-quickstart.md
> +1. Click **Copy credentials** save your credentials in a secure location.
```suggestion
1. Click **Copy credentials** and save your credentials in a secure location.
```

2021-09-10 02:39 UTC, ddhodge commented on docs/content/latest/yugabyte-cloud/cloud-basics/add-connections.md
> +Yugabyte Cloud only allows client connections to clusters from entries in IP allow lists that have been explicitly assigned to the cluster. Each entry can either be a single IP address, a CIDR-notate
Allow lists can be assigned to and shared among any cluster, and clusters can have any number of allow lists.

2021-09-14 04:41 UTC, pavithra-yb commented on docs/content/latest/yugabyte-cloud/cloud-basics/connect-to-clusters.md
>  - `<DB PASSWORD>` with your database username.
<DB PASSWORD>` with your database password.

2021-09-14 05:35 UTC, merged